### ISSUE TITLE
CSS margin is ignored

### ISSUE THREAD

**Issue by PlainBane** [windicss/vite-plugin-windicss#100]
**Describe the bug**
If css margin is used windicss ignores it.

**Minimal Reproductions**
```
<div class="test-container">
</div>

.test-container {
        display: flex;
        width: 80%;
        margin: 0 auto 0 auto; /* This is ignored completely */
        margin-right: auto; /* This works */
        margin-left: auto;  /*  Second margin is ignored /*
    }

```
**Versions**
- vite-plugin-windicss: 0.11.1
- vite: 2.1.2
- framework: svelte

**Comment by antfu** [comment]
What's the source code that triggers your problem? Can you share a minimal reproduction for us the investigate?

**Comment by PlainBane** [comment]
Tried to reproduce the issue today and it's gone. Must be something to do with my system / browser then. System restart might have resolved it.
