### ISSUE TITLE
Custom layers overwrite utility class

### ISSUE THREAD

**Issue by pedrodim** [windicss/vite-plugin-windicss#104]
**Describe the bug**

When declaring custom layers on a custom css entry (say `index.css` imported after `windi.css`) all the layers declared inside have precedence over the utilities classes or any other windi layer as all the layers appear before the custom layers.

Windi CSS correctly reorder the layers when processing the css file (first base, then components and finally utilities) but only on the _context_ of the file, so importing `windi.css` first and then `index.css` keeps the base utilities always before any custom component declared on the css file, making it impossible to use them to overwrite some style of the component (unless `!` is used on the utility).

**Minimal Reproductions**

https://github.com/pedrodim/vite-plugin-windicss-layers

```js
import 'virtual:windi.css'
import './index.css'
```

```css
@layer components {
  .btn {
    @apply bg-blue-600;
  }
}
```

```html
<button class="btn bg-red-500">
  Button
</button>
```

**Expectative behaviour**: button is red
**Actual result**: button is blue

**Versions**
- vite-plugin-windicss: 0.9.7
- vite: 2.1.2

**Additonal Context**

This is not a problem with tailwind as all the generated classes are embedded directly on the css file with the tailwind at-rule, thus it correctly orders all custom declared layers. Maybe this plugin could accept an include option with a path to a css file to append together with all the generated classes so it can correctly reorder the layers declared inside?

As a workaround inverting the order of the imports (first css, then windicss) makes the utility classes work again, but this moves the problem the other way around, properties from preflight or any other generated class cannot be overwritten on the css file.

**Comment by antfu** [comment]
My proposal solution for that

```ts
import 'virtual:windi-base.css'
import 'virtual:windi-components.css'
import 'virtual:windi-utilities.css'
import './index.css'
```

So your declarations with `@layer components` will be removed from `index.css` and append to `virtual:windi-components.css`. WDTY?

If that works for you, I will try to work with windicss core and bring this feature.

**Comment by pedrodim** [comment]
> So your declarations with @layer components will be removed from index.css and append to virtual:windi-components.css. WDTY?

That sounds great!

But why do we need multiple windi imports? Couldn't just one `import 'virtual:windi.css'` work as well?
In any case, your idea totally works for me.

**Comment by antfu** [comment]
Yeah, the reason for using multiple imports is that you might need to have better controls over their ordering. For example:

```css
import 'virtual:windi-base.css'
import 'virtual:windi-components.css'
import './index.css'
import 'virtual:windi-utilities.css'
```

But that said, `import 'virtual:windi.css'` will always work as importing them one-by-one.

**Comment by antfu** [comment]
https://github.com/windicss/vite-plugin-windicss/pull/138
