### ISSUE TITLE
(plugin rollup-plugin-windicss:groups) TypeError: Cannot read property 'isDetectTarget' of undefined.

### ISSUE THREAD

**Issue by vvni** [windicss/vite-plugin-windicss#106]
**Describe the bug**

![image](https://user-images.githubusercontent.com/50414099/112272764-8ef11480-8cb7-11eb-80f1-3b0cae8e37a4.png)

**Minimal Reproductions**

[rollup-plugin-windicss-demo](https://github.com/vvni/rollup-plugin-windicss-demo)
**Versions**
- rollup-plugin-windicss: 0.9.8

**Comment by vvni** [comment]
(plugin rollup-plugin-windicss:entry) TypeError: Could not load /@windicss/windi.css (imported by src/index.ts): Cannot read property 'interpret' of undefined.

**Comment by vvni** [comment]
![image](https://user-images.githubusercontent.com/50414099/112279465-e9da3a00-8cbe-11eb-863a-ac0858c9a8c0.png)

![image](https://user-images.githubusercontent.com/50414099/112279479-ef378480-8cbe-11eb-99c8-1208949b8869.png)

**Comment by vvni** [comment]
Do I need to create a new issue?

**Comment by antfu** [comment]
It's a bug and should be fixed in 0.9.11. But I still can't get your repro running correctly, it seems like you will need to have some plugins to handle css files for rollup.

**Comment by vvni** [comment]
Yes, I want to make a component library。
