### ISSUE TITLE
TypeError: Could not load /@windicss/windi.css (imported by src/index.ts): Cannot read property 'interpret' of undefined.

### ISSUE THREAD

**Issue by vvni** [windicss/vite-plugin-windicss#107]
**Describe the bug**

![image](https://user-images.githubusercontent.com/50414099/112279465-e9da3a00-8cbe-11eb-863a-ac0858c9a8c0.png)

![image](https://user-images.githubusercontent.com/50414099/112279479-ef378480-8cbe-11eb-99c8-1208949b8869.png)
**Minimal Reproductions**

[rollup-plugin-windicss-demo](https://github.com/vvni/rollup-plugin-windicss-demo)
**Versions**
- rollup-plugin-windicss: 0.9.10

**Comment by antfu** [comment]
See #106
