### ISSUE TITLE
Can't use variants inside @apply in Svelte components

### ISSUE THREAD

**Issue by www-chique** [windicss/vite-plugin-windicss#108]
**Describe the bug**
Trying to use the variants with apply in Svelte component <style> does not work

**Minimal Reproductions**
```
<style>
	@layer components {
		.control-button {
			@apply hover:bg-red-500;
		}
	}
</style>
```

**Versions**
"rollup-plugin-windicss": "^0.9.11",
- Using within Routify/Svelte

**Additonal Context**
![image](https://user-images.githubusercontent.com/29447216/112484426-ee2a5400-8d9f-11eb-887a-37f0894a85b3.png)

**Comment by antfu** [comment]
#98
