### ISSUE TITLE
Bulk Add Colors

### ISSUE THREAD

**Issue by go4cas** [windicss/vite-plugin-windicss#109]
I use a lot of dynamic colors in my code, using e.g. `bg-{state}-500`.

Is there an easy way to bulk add a set of colors to the config, or do I have to manually safest each used color:
```javascript
    WindiCSS({
      scan: {
        fileExtensions: ['html', 'js', 'vue']
      },
      safelist: [
        'bg-blue-50 bg-blue-100 bg blue-200 ...',
        'bg-red-50 bg-red-100 bg red-200 ...',
      ]

```

**Comment by go4cas** [comment]
I have managed to get this right, adding the following to the `site.config.js`, but this feels very hacky:
```javascript
function colorList() {
  const types = [
    'bg',
    'text',
    'border'
  ]
  const colors = [
    'blue',
    'red',
    'green',
    'yellow'
  ]
  const sizes = [
    '50','100','200','300','400','500','600','700','800','900'
  ]
  let colorSet = []
  types.forEach(type => {
    colors.forEach(color => {
      sizes.forEach(size => {
        colorSet.push(`${type}-${color}-${size}`)
      })
    })
  })
  return colorSet.join(' ')
}
const colors = colorList()

export default defineConfig({
  plugins: [
    vue(),
    ViteComponents(),
    WindiCSS({
      config: './tailwind.config.js',
      scan: {
        fileExtensions: ['html', 'js', 'vue']
      },
      safelist: [
      .....
        colors
      ]
    })
  ],
})

```

**Comment by antfu** [comment]
I'd think it's a good way to go, or otherwise, what do you imagine the API would look like for your usage?

**Comment by go4cas** [comment]
Thanks for the reply, @antfu! I was thinking about this, and I cannot think of a practical way to deal with dynamic classes.

So, for now I'm just creating a helper lib, whereby I can pass in a selection of base windi classes and then get back the relevant safelist classes, i.e. a combination of your `range(size, startAt = 1)` example and my `forEach` example, so that the `vite.config.js` can import and use.

I am sure, in future, you will come up with a smarter way of doing this :)
