### ISSUE TITLE
Classes with parentheses doesn't work

### ISSUE THREAD

**Issue by bdrtsky** [windicss/vite-plugin-windicss#111]
Hi!

Previously I used this in my `tailwind.config`

```
height: theme => ({
        '(custom)': `calc(100% - ${theme('spacing.18')})`,
})
```

And then used class like `h-(custom)`. But after I moved to Windi noticed that this classes are not generated anymore.

My test `windi.config`

```
module.exports = {
  theme: {
    extend: {
      height: theme => ({
        '(hello)': '1000px'
      }),
    }
  }
}
```

PS: love what Windi did with Tailwind DX, thank you 😍

**Comment by antfu** [comment]
Before adding the parentheses to the regex rules, I am a bit curious about the reason to use them in the class name. My concern is that case would be confusing with the variant group `hover:(text-bold border-none)` feature. Would be appreciated if you can share a bit more context on this, thanks.

**Comment by bdrtsky** [comment]
Oh, I see your concern. 

My usage for parentheses is for classes, that using some kind of `calc`, for example `h-(screen-18)` translates to `height: calc(100vh - 4.5rem)` and so on.
