### ISSUE TITLE
Custom font family not applied

### ISSUE THREAD

**Issue by secondary-school55** [windicss/vite-plugin-windicss#114]
**Describe the bug**

Custom font family variant is not applied.

**Minimal Reproductions**

tailwind.config.cjs
```
module.exports = {
  theme: {
    fontFamily: {
      corsiva: "monotype corsiva",
    },
  },
};
```

svelte.config.cjs
```
const static = require("@sveltejs/adapter-static");
const windiCSS = require("vite-plugin-windicss").default;
const pkg = require("./package.json");

/** @type {import('@sveltejs/kit').Config} */
module.exports = {
  kit: {
    adapter: static(),
    target: "#svelte",
    vite: {
      plugins: [windiCSS()],
      ssr: {
        noExternal: Object.keys(pkg.dependencies || {}),
      },
    },
  },
};
```

App.svelte
```
<div class="font-corsiva">Hello world</div>
```
```
**Versions**
- vite-plugin-windicss: 0.9.11
- vite: 2.1.2
- framework(vue/react/svelte/etc):
- sveltekit: 1.0.0-next.59
**Additonal Context**

**Comment by antfu** [comment]
See 599e28c, it works fine for me. Where is your `App.svelte` located? By default, this plugin only scans for files under `src/` folder. You can refer to the readme for more deails.

**Comment by dioxine** [comment]
I have the same problem. To test works it or not, i added `console.log('blabla')` in tailwind.config.cjs and got nothing, when app starts in dev mode. When i remove `type: "module"`  from package.json, and rename tailwind.config.cjs to tailwind.config.js, everything works ok! Seems  vite-plugin-windicss can get only .js config. Unfortunately, SvelteKit does not allow you to build app with adapter-node, when there is no  `type: "module"`  in package.json. Please add support for .cjs extension!

**Comment by dioxine** [comment]
everything works now! thanx!
