### ISSUE TITLE
After upgrading to 0.10, my project style is completely messed up.

### ISSUE THREAD

**Issue by chad-bin** [windicss/vite-plugin-windicss#115]
**Describe the bug**

After upgrading to 0.10, my project style is completely messed up
**Minimal Reproductions**

**Versions**
- vite-plugin-windicss:
- vite:
- framework(vue/react/svelte/etc):

**Additonal Context**

**Comment by antfu** [comment]
Looking into it right now

**Comment by antfu** [comment]
It's introduced in 0.10.1 and should be fixed in 0.10.2. Thanks
