### ISSUE TITLE
can not found className list and not working in chrome devtools's Styles tab(.cls)

### ISSUE THREAD

**Issue by ErrorJe** [windicss/vite-plugin-windicss#116]
**Describe the bug**

i can try any Utility className in the Chrome devtools's tab (.cls) when i use `tailwind` , and working immediately on current page。
but that can't working when use `windi` . what can i do that solving this problem?

**Minimal Reproductions**

none

**Versions**
- vite-plugin-windicss:0.9.11
- vite:2.1.3
- framework(vue/react/svelte/etc):vue

**Additonal Context**
![image](https://user-images.githubusercontent.com/33750626/112633459-577b9700-8e74-11eb-9b33-1e435af7c0b8.png)

**Comment by antfu** [comment]
Do you have this enabled?
https://github.com/windicss/vite-plugin-windicss#design-in-devtools

**Comment by ErrorJe** [comment]
> Do you have this enabled?
> https://github.com/windicss/vite-plugin-windicss#design-in-devtools

Yes I have. that just provide className list but not working by picking some class

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by ErrorJe** [comment]
> Can you share a minimal reproduction? Thanks.

look this repository https://github.com/windicss/vite-plugin-windicss/issues/116#issuecomment-808699208

**Comment by ErrorJe** [comment]
> Can you share a minimal reproduction? Thanks.

ok this is that https://github.com/ErrorJe/vue3-vite-windi

**Comment by ErrorJe** [comment]
i guess `tailwind` provide complete .css file in browser, and `windi` not do this。

**Comment by antfu** [comment]
![image](https://user-images.githubusercontent.com/11247099/112792006-380f8480-9095-11eb-999f-b9c42c0c5537.png)

It seems like it works well to me. Can you test out more about your environment? Thanks

**Comment by ErrorJe** [comment]
> ![image](https://user-images.githubusercontent.com/11247099/112792006-380f8480-9095-11eb-999f-b9c42c0c5537.png)
> 
> It seems like it works well to me. Can you test out more about your environment? Thanks

you can try more className, it always only 1-2 items can working

**Comment by ErrorJe** [comment]
> ![image](https://user-images.githubusercontent.com/11247099/112792006-380f8480-9095-11eb-999f-b9c42c0c5537.png)
> 
> It seems like it works well to me. Can you test out more about your environment? Thanks

you can try more className, it always only 1-2 items can working

**Comment by antfu** [comment]
Thanks! Should be fixed in 0.11.1
