### ISSUE TITLE
"Design in DevTools" does not work in WSL 2

### ISSUE THREAD

**Issue by nandordudas** [windicss/vite-plugin-windicss#123]
**Describe the bug**
Im using wsl 2, embedded browser have some restrictions:
- cannot add new workspace under Sources/Filesystem panel - i tried to bridge the problem,
- cannot edit html under Elements panel - if i edit .cls, has no effect too.

**Minimal Reproductions**
I have cloned vitesse repository and try to override a class from embedded and external browser.

**Versions**
- vite-plugin-windicss: 0.10.4
- vite: 2.1.3
- vue: 3.0.9

**Additonal Context**
This behaviour is not related to plugin, it is belongs to the environment - i think.

**Comment by antfu** [comment]
Might relate to #116, can you try it with v0.11.1? Thanks.

**Comment by nandordudas** [comment]
> Might relate to #116, can you try it with v0.11.1? Thanks.

Here is a [video](https://youtu.be/pkKZKQlErD0)

**Comment by antfu** [comment]
Vitesse didn't enable the devtools support - until now. Can you check if you have `import 'virtual:windi-devtools'` in your code? 

Otherwise, I'd like to see the Network tab of your devtools. Thank

**Comment by nandordudas** [comment]
> Vitesse didn't enable the devtools support - until now. Can you check if you have `import 'virtual:windi-devtools'` in your code?

It works - i can see `[windicss] devtools support enabled` message in console tab.
Just import the windi'a devtool 🤐
