### ISSUE TITLE
页面刷新缓慢

### ISSUE THREAD

**Issue by chad-bin** [windicss/vite-plugin-windicss#124]
**Describe the bug**

最近的更新好像开始出现刷新缓慢，感觉开始变卡，内存溢出的感觉。我的电脑内存大，都很卡

**Minimal Reproductions**

**Versions**
- vite-plugin-windicss:
- vite:
- framework(vue/react/svelte/etc):

**Additonal Context**

**Comment by antfu** [comment]
What's the version you are using? Can you share a minimal repro? THanks
