### ISSUE TITLE
Memory overflow

### ISSUE THREAD

**Issue by anncwb** [windicss/vite-plugin-windicss#125]
**Describe the bug**

After upgrading to 0.11.2, the memory overflow seems to start to appear again

Windicss cause hot updates to be very slow

See specifically #58

**Minimal Reproductions**

**Versions**
- vite-plugin-windicss: 0.11.2
- vite:2.1.5
- framework(vue/react/svelte/etc):vue

**Additonal Context**

**Comment by anncwb** [comment]
![image](https://user-images.githubusercontent.com/28132598/113092447-90bf5880-9220-11eb-914b-b293f712c89a.png)

**Comment by anncwb** [comment]
Same problem as #58, simple examples may not reproduce

**Comment by anncwb** [comment]
I reverted back to 0.10.4 and the problem disappeared

**Comment by antfu** [comment]
Added a memory logger to 0.11.3, you can check out by running `DEBUG=vite-plugin-windicss:memory vite`. Would love to have more info on this to investigate. Thanks.

**Comment by anncwb** [comment]
@antfu  

![image](https://user-images.githubusercontent.com/28132598/113096689-4215bc80-9228-11eb-966b-8ec8da64008e.png)

**Comment by anncwb** [comment]
@antfu  I have a simple test, the memory is superimposed on components.(Please ignore the error message)

![image](https://user-images.githubusercontent.com/28132598/113096760-640f3f00-9228-11eb-8c23-7d08fcc2b166.png)

**Comment by antfu** [comment]
What changes did you made?

**Comment by anncwb** [comment]
I simulate normal development and modify the class at will. During this period, the browser was not refreshed.
![image](https://user-images.githubusercontent.com/28132598/113096879-9faa0900-9228-11eb-9f04-323cf191993a.png)

**Comment by anncwb** [comment]
> What changes have you made? Especially wonder about the 500MB -> 1000MB jumps

This should be caused by my changing from my-4 to my-20

**Comment by anncwb** [comment]
Try to modify some larger numbers, such as mr-30 mr-20. The memory will increase and will not be recycled

**Comment by antfu** [comment]
The weird thing is that it doesn't happen to me. Can you try with this again?

`DEBUG=vite-plugin-windicss:compile,vite-plugin-windicss:memory vite`

or 

`DEBUG=vite-plugin-windicss:* vite`

It really confused me, appreciate the help!

**Comment by anncwb** [comment]
I'm trying a few more times. Give you feedback later

**Comment by antfu** [comment]
Maybe you can try this package to dump the heap and inspect in Chrome to see where is the memory located

https://www.npmjs.com/package/heapdump

**Comment by anncwb** [comment]
I set a relatively large value in order to quickly restore it, and it is easy to appear. However, this is generally not done. In actual development, the components are generally accumulated after multiple modifications, and then reach this amount

![image](https://user-images.githubusercontent.com/28132598/113098925-ba31b180-922b-11eb-81fc-dac90db5e9dd.png)

**Comment by anncwb** [comment]
> Maybe you can try this package to dump the heap and inspect it in Chrome to see where is the most memory located
> 
> https://www.npmjs.com/package/heapdump

Thanks, let me try

**Comment by anncwb** [comment]
Sorry, I have been busy dealing with other things these days and forgot. I feel that the picture above can be reproduced. I tried to switch to the jit mode of taliwindcss, and the problem disappeared.
If you don't mind, you can try to look at the project https://github.com/anncwb/vue-vben-admin, it's a bit messy.

**Comment by anncwb** [comment]
@antfu Can you see what is wrong with this, because I am not the only one who appears. Many people have given me feedback on this, and almost everyone will show up. The most common time for this: when you write a page from scratch, and continue to increase the class to achieve the page, there is a great chance that it will appear at this time

**Comment by antfu** [comment]
Well, I would love to improve this but sadly it does not seem to appear to me. I don't see any potential point that causing the memory leakage. I'd be appreciated if anyone could go through the code and see if there is anything we can improve. Thanks.

**Comment by anncwb** [comment]
![image](https://user-images.githubusercontent.com/28132598/119814170-b0bb8180-bf1c-11eb-95fc-3ccdaedd9b6a.png)

@antfu  I tried to debug, the memory overflow seems to be related to style. After I empty here, the memory overflow disappears, but the style will lose the left and right after emptying. Do you have any good ideas

**Comment by antfu** [comment]
It's a few versions behind, have you tried with the latest one?

**Comment by anncwb** [comment]
Have tried, because 0.11.3 has a memory record debug, so I fall back to this version for testing

**Comment by anncwb** [comment]
@antfu  Since github does not support gif upload, I sent a gif to your mailbox: ` hi@antfu.me`, you can see how I appeared

**Comment by anncwb** [comment]
This problem has bothered me for a long time. I have been trying to troubleshoot, but I have not been able to find the reason 😂

**Comment by antfu** [comment]
In the latest version, we no longer uses the code you mentioned.

Do you have any plugins that process css as well? I have never faced this issue myself, so I guess it might related to windi's HMR triggers some other plugin to not clear their cache or something?
