### ISSUE TITLE
sveltekit not working anymore with v0.12.x

### ISSUE THREAD

**Issue by eikaramba** [windicss/vite-plugin-windicss#126]
**Describe the bug**
with v0.11.8 it worked, every version after tailwind classes are not there anymore

**Minimal Reproductions**
i have exact code from [sveltekit documentation](https://windicss.org/guide/svelte.html#sveltekit) from frontpage

**Comment by antfu** [comment]
Are you using Windows? Can you try with v0.12.3? Thanks

**Comment by eikaramba** [comment]
yes i am using windows and your fix solved it! thank you very much :)
