### ISSUE TITLE
[question]: is chrome locale override a bad idea

### ISSUE THREAD

**Issue by nandordudas** [windicss/vite-plugin-windicss#128]
[chrome local override](https://developer.chrome.com/blog/new-in-devtools-65/#overrides)

This is only "one step faster" opinion.

**Comment by antfu** [comment]
Not sure if you got you, can you explain it a bit more? Thanks

**Comment by nandordudas** [comment]
> Not sure if you got you, can you explain it a bit more? Thanks

Sometimes, only for demonstrate few css changes i have opened a project with chrome filesystem. This is a lazy solution. In this case i make changes with devtools and these changes are available, because chrome modifiy the given files.

Eg.: folder is created (C:\Users\...\Desktop\...), open this folder with chrome filesystem (with file protocol), enable persistent overrides and all changes from chrome are available in files.

Very common use case is making changes in chrome (small changes) and copy or rewrite it in style or html part. But with the lazy mode, changes are available just in time.

I dont have any idea, how can be enable in embedded browser, and what side effects can be happen (css prop is changed, file written, compiler detects the change, recompile code, ...).

Is this good enough? :)

**Comment by antfu** [comment]
Maybe try with https://github.com/antfu/windicss-runtime-dom?
