### ISSUE TITLE
0.13.0 breaks custom colors

### ISSUE THREAD

**Issue by eikaramba** [windicss/vite-plugin-windicss#133]
I updated from v0.12.5 to v0.13.0 and now my **custom colors are not working anymore**.

i also tried to change my `windi.config.js` file to use defineConfig but still not working. before i used plain `module.exports`

```
import { defineConfig } from 'windicss/helpers'

export default defineConfig({
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      blue: {
        dark: '#ff00ff',
      },
      green: {
        DEFAULT: '#ffff00'
      }
......
```

Windows x64
"@sveltejs/kit": "next",
"svelte": "^3.37.0",
"svelte-preprocess": "^4.7.0",
"vite": "^2.1.5",
"vite-plugin-windicss": "^0.13.0"

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by alexanderniebuhr** [comment]
@antfu this is windows bug, of filesystem.. caused by some import and require stuff.. same as #134 .. I have fixed it in one project of mine with `pathToFileURL`
https://github.com/alexanderniebuhr/sveasy/blob/152e7ef53b953453f0703ad904cd7b2fee7781fc/src/utils/index.ts#L11

**Comment by antfu** [comment]
@alexanderniebuhr Can you make a PR for it? Thanks!
