### ISSUE TITLE
HMR fails to update windi config file when using a .js extension

### ISSUE THREAD

**Issue by TrentWest7190** [windicss/vite-plugin-windicss#139]
**Describe the bug**
When updating `windi.config.js`, the HMR appears to hang after receiving the message `configure file changed, reloading`.

`vite.config.js`
```
import {defineConfig} from 'vite'
import reactRefresh from '@vitejs/plugin-react-refresh'
import WindiCSS from 'vite-plugin-windicss'

export default defineConfig({
    plugins: [
        reactRefresh(),
        WindiCSS({
            scan: {
                dirs: ['project/**/*'],
                fileExtensions: ['js', 'jsx'],
                include: ['./windi.config.js'],
                exclude: ['node_modules', '.git'],
            },
        }),
    ],
})
```

`windi.config.js`
```
import {defineConfig} from '@windicss/plugin-utils'

export default defineConfig({
    theme: {
        colors: {
            gray: {
                200: '#D1D6DE',
                300: '#A8B1BF',
                400: 'orange',
                500: 'green',
            },
        },
    },
})

```

For example, I change `theme.colors.gray.400` to any other value, the console gives the following message:
```
2:04:21 PM [vite] hmr update /@windicss/windi.css
configure file changed, reloading
```

However, the reload appears to hang, as it never actually resolves and reloads the config. Instead I have to stop the vite process entirely and restart it to see the changes. This occurs every time I update the windi config.

**Versions**
- vite-plugin-windicss: v0.14.0, also reproducible on v0.13.2
- vite: v2.1.5
- framework(vue/react/svelte/etc): react

**Additonal Context**
I'm running this inside of a WSL2 instance which itself is running Ubuntu 18.04.4 LTS

**Comment by TrentWest7190** [comment]
After enabling hmr debugging, it seems that the hot reload actually _is_ going through, my mistake.

```
  vite-plugin-windicss:hmr config file changed: /ui/windi.config.js +0ms
2:29:20 PM [vite] hmr update /@windicss/windi.css
configure file changed, reloading
  vite-plugin-windicss:hmr config file changed: /ui/windi.config.js +1s
2:29:21 PM [vite] hmr update /@windicss/windi.css (x2)
configure file changed, reloading
  vite-plugin-windicss:hmr config file changed: /ui/windi.config.js +2s
2:29:23 PM [vite] hmr update /@windicss/windi.css (x3)
configure file changed, reloading
  vite-plugin-windicss:hmr config file changed: /ui/windi.config.js +2s
2:29:25 PM [vite] hmr update /@windicss/windi.css (x4)
configure file changed, reloading
  vite-plugin-windicss:hmr config file changed: /ui/windi.config.js +13s
2:29:38 PM [vite] hmr update /@windicss/windi.css (x5)
configure file changed, reloading
```

However, inspecting the generated `windi.css` file shows that the updated windi config is not being taken into account when loaded in the browser. Changing any value within the config does not cause the generate css file to update.

**Comment by TrentWest7190** [comment]
Looking through the code, I saw a code path split with the condition of the windi config file ending in a `.js` extension. Curious, I changed the extension to `.ts` without changing anything in the file itself, and amazingly, it worked! So, it appears there may be something wrong with that code block.

`packages/plugin-utils/src/resolveOptions.ts line 228`
```
if (configFilePath.endsWith('.js')) {
  // hack to prevent `import` get transformed
  // eslint-disable-next-line no-new-func
  const _import = new Function('modulePath', 'return import(modulePath)')
  
  resolved = (await _import(pathToFileURL(configFilePath)))?.default || {}
  if (resolved.default)
    resolved = resolved.default
  }
  else {
  delete require.cache[require.resolve(configFilePath)]
  resolved = require(configFilePath)
  if (resolved.default)
    resolved = resolved.default
  }
```

Unfortunately I'm unfamiliar with what exactly this is doing, so I can't provide any more information. I will update the title of the ticket to accurately reflect the bug in question.

**Comment by alexanderniebuhr** [comment]
@TrentWest7190 that code block allows the config to be either `.mjs, .cjs, .ts, .js` or `type: module`
for me it sound's like an caching issue.. not very sure

**Comment by yannxaver** [comment]
Just wanted to add that I faced the same problem while using the following packages:

```
"dependencies": {
    "vue": "^3.0.5"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.2.3",
    "@vue/compiler-sfc": "^3.0.5",
    "vite": "^2.3.5",
    "vite-plugin-components": "^0.10.4",
    "vite-plugin-windicss": "^1.0.1",
    "windicss": "^3.1.1"
  }
```

Changing `tailwind.config.js` to `tailwind.config.ts` did solve the problem for me as well.
