### ISSUE TITLE
windicss does not pick my configuration in tailwind.config.js file when changing root config in vite.config.js

### ISSUE THREAD

**Issue by samadadi** [windicss/vite-plugin-windicss#140]
**Describe the bug**

Hi. when I am changing **root** config in vite.config.js file to **src** folder and moving index.html file to this root folder, windicss does not pick my configuration in tailwind.config.js file. But when I remove **root** config and move index.html file back to where vite.config.js file is, everything works file. What am I doing wrong?

**Versions**
- vite-plugin-windicss: 0.14.0
- vite: 2.1.5
- framework(vue/react/svelte/etc): solid-js

**Comment by antfu** [comment]
It will search `tailwind.config.js` **under** your project root. You can either move your `tailwind.config.js` to your new root or configure the path explicitly.

```ts
WindiCSS({
  config: path.resolve(__dirname, 'tailwind.config.js'),
})
```

**Comment by samadadi** [comment]
moving tailwind.config.js to root folder works but setting this configuration does not work.


    import solid from 'vite-plugin-solid';
    import windi from 'vite-plugin-windicss';
    import path from 'path';

    const windiOpts = {
        scan: {
             dirs: ['.'],
             fileExtensions: ['html', 'js', 'jsx', 'ts', 'tsx'],
              config: path.resolve(__dirname, 'tailwind.config.js')
          }
     };

    export default {
           root: 'src',
          plugins: [
           solid({}),
           windi(windiOpts)
          ],
           build: {
              target: 'esnext',
              polyfillDynamicImport: false
        }
     };

**Comment by samadadi** [comment]
I am so sorry. I did a stupid mistake and your response was helpful than you so much.
