### ISSUE TITLE
Provide proper warning on using unknown layers

### ISSUE THREAD

**Issue by pedrodim** [windicss/vite-plugin-windicss#145]
It seems #138 introduced a bug with the layer directive, I would expect from the content to get removed from the css entry and moved to the correct position (either windi virtual entries or reordered in the same entry file) but instead it gets totally removed from the output styles.

**Minimal Reproductions**
```ts
import 'virtual:windi-base.css';
import 'virtual:windi-components.css';
import './my-styles.css';
import 'virtual:windi-utilities.css';
```

```css
/* my-styles.css */
@layer component {
  .button {
    @apply font-medium;
  }
}
```

The resulting styles doesn't contain `.button` class.

**Versions**
- vite-plugin-windicss: 0.14.0
- vite: 2.1.5

**Comment by antfu** [comment]
Shouldn't the layer be `components`? I do agree we can add a warning on using unsupported layers.

**Comment by pedrodim** [comment]
My bad, that was a typo. You can see the problem I'm referring to here: https://codesandbox.io/s/nervous-water-fbtme?file=/src/styles.css the button should be blue instead the class instead gets removed.

**Comment by antfu** [comment]
The weird thing is that it IS blue on my side 😅

![image](https://user-images.githubusercontent.com/11247099/115408469-75de7380-a223-11eb-9eb7-2a808d5b59b8.png)

**Comment by pedrodim** [comment]
Weird, sometimes it does appear blue but if I restart the server/sandbox then it lost the color again.

<img width="702" alt="Screenshot 2021-04-21 at 12 56 14" src="https://user-images.githubusercontent.com/2473843/115542825-f7c0b200-a2a0-11eb-934c-edcab1e3e766.png">

I try to make it closer to what I have, could you check again? [Same link](https://codesandbox.io/s/nervous-water-fbtme?file=/src/styles.css) as before.

Also, [this other issue](https://github.com/windicss/windicss/issues/263) seems exactly like the issue I'm having.
