### ISSUE TITLE
Is there a way to have multiple tailwind configurations  in a project?

### ISSUE THREAD

**Issue by ahku** [windicss/vite-plugin-windicss#148]
For example separate configuration for the back and frontend. 

Couls not find a way to point to a specific configuration file.

**Comment by antfu** [comment]
For vite plugin:

```ts
WindiCSS({
  config: 'path/to/windi.backend.config.js'
})
```

**Comment by ahku** [comment]
Wow, this is great! I was thinking that I will have to use pure vanilla css for the backend in order to keep it in the same repo!
