### ISSUE TITLE
Propagation issue when using conditional component is=""

### ISSUE THREAD

**Issue by gawlk** [windicss/vite-plugin-windicss#15]
Hi,

When using `<component is="x ? 'button' : 'a'">` the font for example won't propagate to the component

Here's a demo: https://github.com/gawlk/windicss-propagation-issue

**Comment by antfu** [comment]
It's not possible for the plugin to aware that, you can specify them by:

```ts
...WindiCSS({
  preflight: {
    safelist: 'button a'
  }
})
```

**Comment by gawlk** [comment]
Alright thanks !
