### ISSUE TITLE
Confused about safelist

### ISSUE THREAD

**Issue by qgates** [windicss/vite-plugin-windicss#156]
Apologies for writing here, this may be partly an issue or it may be misunderstanding. Building my app for production today and a seemingly random selection of styles weren't compiling through. Everything works fine using `npm run dev` but breaks using 'npm run build'. Adding the missing styles to `safelist` has fixed things, but I'm left confused as to what needs does and does not need adding and why.

Here's a snippet:
```html
<div class="absolute z-20 top-1/3 w-full rounded-xl border-t-10 bg-light-blue-50
  border-light-blue-200 dark:bg-gray-700 dark:border-gray-500 -mx-1 md:-mx-2">
  ...
</div>
```

In dev mode, everything works, but in production the following styles don't compile through: `top-1/3` `border-t-10` `border-light-blue-200` `rounded-xl` `-mx-1` `md:-mx-2`. So I add all these to `safelist` and everything works.

What's confusing especially is why `border-light-blue-200` doesn't work, also `dark:border-gray-500` doesn't work  unless border-light-blue-200 is in `safelist`. Also `rounded-xl`, the negative `-mx-1`, and why `md:-mx-2` needs to be prefixed by the screen breakpoint.

On a more general note it seems fairly arbitrary what works and what doesn't and having to add everything to safelist doesn't really seem like a good approach. Or I'm totally confused, help please!

**Comment by antfu** [comment]
Can you share your repo so I can have a look? Thanks

**Comment by qgates** [comment]
Sorry I can't share repo as this is a project I'm working on for a customer hosted on their private network. I can however share whatever files and content you need.

The project is running vite, with vue using SFC's. Everything's up to date. Here's the package.json:
```json
{
  "name": "smartsel-app",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"
  },
  "devDependencies": {
    "@iconify/json": "^1.1.328",
    "@types/lodash": "^4.14.168",
    "@vitejs/plugin-vue": "^1.2.1",
    "@vue/compiler-sfc": "^3.0.11",
    "rollup-plugin-copy2": "^0.2.0",
    "sass": "^1.32.8",
    "vite": "^2.1.5",
    "vite-plugin-components": "^0.8.3",
    "vite-plugin-icons": "^0.5.0",
    "vite-plugin-pwa": "^0.7.0",
    "vite-plugin-windicss": "^0.14.0"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-solid-svg-icons": "^5.15.3",
    "@fortawesome/vue-fontawesome": "^3.0.0-3",
    "axios": "^0.21.1",
    "dexie": "^3.0.3",
    "jquery": "^3.2",
    "lodash": "^4.17.21",
    "vue": "^3.0.11",
    "vue-router": "^4.0.6"
  }
}
```
app.ts has the following imports:
```ts
import { createApp } from "vue"
import App from "./components/App.vue"
import "./fontawesome"
import "./elog"
import { appdb } from './elog'

import { registerSW } from 'virtual:pwa-register'
import 'virtual:windi.css'
import 'virtual:windi-devtools'

import { createRouter, createWebHashHistory, createWebHistory } from 'vue-router'
...
```
Here's `vite.config.js`:
```js
import Vue from '@vitejs/plugin-vue'
import { defineConfig } from 'vite'
import copy from 'rollup-plugin-copy2'
import { VitePWA } from 'vite-plugin-pwa'
import WindiCSS from 'vite-plugin-windicss'
import Components from 'vite-plugin-components'
import ViteIcons, { ViteIconsResolver } from 'vite-plugin-icons'

export default defineConfig({
    ...
    Vue(),
    VitePWA({ ... }),
    WindiCSS({
      transformCSS: 'pre',
      safelist: 'top-1/3 border-t-10 border-light-blue-200 rounded-xl -mx-1 md:-mx-2'
    }),
    Components({
      customComponentResolvers: ViteIconsResolver({
        componentPrefix: 'icn'
      }),
    }),
    ViteIcons(),
    ...
})
```
The `<div>` from my original post is the top level node of a child component, 2 levels down from App.vue, loaded via vue-router:
```html
<template>
<div class="absolute z-20 top-1/3 w-full rounded-xl border-t-10 bg-light-blue-50 border-light-blue-200 dark:bg-gray-700 dark:border-gray-500
  -mx-1 md:-mx-2" style="box-shadow: 0px -5px 8px rgba(0,0,0,.3)">
    <div>
        ....
    </div>
</div>
</template>
```

Everything works fine via `npm run dev`. The issue is with `npm run build`.

Let me know if you need anything else - TIA 🙂

**Comment by qgates** [comment]
Hi @antfu think I got to the bottom of it. It seems that if I split my `class` over two lines, ie:

```html
<div class="absolute z-20 top-1/3 w-full rounded-xl border-t-10 bg-light-blue-50 border-light-blue-200 dark:bg-gray-700 dark:border-gray-500
  -mx-1 md:-mx-2" style="box-shadow: 0px -5px 8px rgba(0,0,0,.3)">
```
...the problem occurs. But if I concatenate the above onto one line:
```html
<div class="absolute z-20 top-1/3 w-full rounded-xl border-t-10 bg-light-blue-50 border-light-blue-200 dark:bg-gray-700 dark:border-gray-500 -mx-1 md:-mx-2" style="box-shadow: 0px -5px 8px rgba(0,0,0,.3)">
```
...the problem is fixed, ie. everything works, no need for safelist. So I think we may have a bug in windicss.

I say again **there is no problem when running vite in dev mode** ie. `npm run dev`. The problem only occurs when building for production with `npm run build`.

In sum:

If I build for production with the `class` split across two lines as above, a number of the classes don't compile, seems arbitrary as to which.

Whereas, if I concatenate `class` so that everything is on one line as above, everything works as expected.

I've built a sandbox to test this in vitesse, let me know if you need and I'll push it up.

Final thought fwiw, I am building these vite projects on Win10 locally, so line endings (CRLF) may be coming into play with windi's parsing in production?

**Comment by antfu** [comment]
That's interesting, I think we should support multi-line. Yeah, guess it could be the CRLF thing. Will have a look

**Comment by qgates** [comment]
Thanks @antfu that's fixed. Wasn't too sure about why things were working in dev mode but not production so didn't know exactly where to look to fix the regexes, presumably locally installed windicss is compiled down as I couldn't find `plugin-utils` locally?

Thanks again. Does it help to rename the issue?

**Comment by qgates** [comment]
Star 👍⭐

**Comment by qgates** [comment]
@antfu since update to 0.15.9 vite hmr (npm run dev) got very slow, 5-10 seconds after saving file before the vite terminal shows `hmr update`. It's also failing to update in the browser, often requiring a page reload to see the changes. I'm also seeing a lot of `hmr update /@windicss/windi.css` in the terminal and browser. Also nodejs CPU spikes to 8% on one core for 5-10 seconds every time I save a file. 

Rolling back to 0.15.8 everything is fine. Probably wise to leave `latest` at 0.15.8 for other users until this is ironed out as it seems to affect some of my .vue files.

**Comment by antfu** [comment]
@qgates can you verify if it still occur in 0.15.10? Thanks

**Comment by qgates** [comment]
@antfu 0.15.10 has fixed the issue, nice and fast again with updates in dev mode. Also tested with production build for the original issue and everything is correct. Many thanks 🙂
