### ISSUE TITLE
Single quote in a HTML comment and Vue's class object syntax breaks windicss

### ISSUE THREAD

**Issue by FallDownTheSystem** [windicss/vite-plugin-windicss#162]
**Describe the bug**
Vue class object syntax breaks windicss, if the key of the object contains a quotation mark (') AND there's an HTML comment with an odd number of the same quotation mark
```html
<!-- We've used an odd single quote in this comment, and below -->
<div :class="{ 'active': true }">
  Stuff here
</div>
<div class="bg-blue-100">
  More stuff here
</div>
```
These lines do not need to be after each other.

There are no errors, a background class (bg-blue-100) gets generated but without any declarations, so just an empty rule
`.bg-blue-100 {}`

**Versions**
- vite-plugin-windicss: 0.16.0-beta.13
- windicss 3.0.0-beta.6
- vite: 2.2.4

**Additonal Context**
This isn't an actual Vue project, it's a simple HTML page, with the entire vue library directly loaded as a direct dependency, though I doubt that matters.

Attributify is not enabled. But the same happens even if it is.

**Comment by antfu** [comment]
Ahm, nice catching. But it's actually a bit tricky and I don't have a decent solution right now that comes to my mind. Maybe we can strip out the comments before doing the extractions, but still maybe not solve the problem completely.

Would like to know if anyone have some better ideas. Thanks.

**Comment by FallDownTheSystem** [comment]
Assuming you're not extracting class names from comments to begin with, I think that would likely work.
The only problem I can think of is that people could be using comments to whitelist class names.

**Comment by antfu** [comment]
An we also have the problem to proper detect comments. `<!-- -->` `/* */` should be fine, but `//` could something be overkill without a parser 🥲

**Comment by FallDownTheSystem** [comment]
I looked at the code. There are extractors for classes and for tags. Is there a reason we couldn't only look for classes inside the tags?
