### ISSUE TITLE
WindiCSS V3.0 Attributify Mode 在 TS + React中出现的ts提示报错问题

### ISSUE THREAD

**Issue by yangchaojun** [windicss/vite-plugin-windicss#164]
**Describe the bug**
当试用React + TypeScript + windicss V3.0 的新功能——Attributify Mode时，ts提示错误，如下图：
![image](https://user-images.githubusercontent.com/28144249/117526480-05439f00-aff8-11eb-92f1-979fac969f10.png)

```
{
	"resource": "/Users/xxx/playground/react-playground/my-ui-lib/src/App.tsx",
<img width="619" alt="WX20210508-115714@2x" src="https://user-images.githubusercontent.com/28144249/117525455-f90a1280-aff4-11eb-813a-53f2fc421eee.png">

	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "不能将类型“{ children: (string | number)[]; bg: string; text: string; font: string; p: string; border: string; onClick: () => void; }”分配给类型“DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>”。\n  类型“DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>”上不存在属性“bg”。",
	"source": "ts",
	"startLineNumber": 9,
	"startColumn": 9,
	"endLineNumber": 9,
	"endColumn": 11
}
```
可能的原因：typescript识别到dom 类型上没有对应的windi css variant属性。

**Versions**
- vite-plugin-windicss: ^0.16.0-beta.14
- windicss: ^3.0.0-beta.6
- vite: ^2.2.3
- framework(vue/react/svelte/etc): react@^17.0.0 @types/react: ^17.0.0,

**Comment by antfu** [comment]
We could extend the interface by

```ts
declare global {
  interface HTMLElement {
    text?: string
    font?: string
    bg?: string
    /* ... */
  }
}
```

Not a React user, can do that but it won't be my high priority. If anyone interested in making a package for that, feel free to do so. Thanks.

**Comment by yangchaojun** [comment]
> We could extend the interface by
> 
> ```ts
> declare global {
>   interface HTMLElement {
>     text?: string
>     font?: string
>     bg?: string
>     /* ... */
>   }
> }
> ```
> 
> Not a React user, can do that but it won't be my high priority. If anyone interested in making a package for that, feel free to do so. Thanks.

Ok, thanks for your suggestion.
