### ISSUE TITLE
CSS Module not working when using @apply in react

### ISSUE THREAD

**Issue by tsanyqudsi** [windicss/vite-plugin-windicss#165]
**Describe the bug**
when i'm using @apply in a class, for example : 
`.topBar {
  @apply flex flex-wrap justify-between px-3 py-2 border-b border-gray-300 fixed w-full 
}`

vite would produce error such as
`[vite] Internal server error: Invalid mapping: {"generated":{"line":3,"column":-1},"source":"Navigation.module.css","original":{"line":2,"column":86},"name":null}`

**Minimal Reproductions**

1. Set up a react vite project
2. Set up `vite-plugin-windicss`
3. Create `[name].module.css`
4. import the css module file using `import styles from 'module/css/path/[name].module.css'`
5. Assign it to any element 

**Versions**
- vite-plugin-windicss: 0.15.10
- vite: 2.2.3
- framework(vue/react/svelte/etc): React

**Comment by winter-ice** [comment]
Same issue in Vue , and I did not use css module.

**Comment by tsanyqudsi** [comment]
@winter-ice after i checked thoroughly apparently `windicss` went into `devDependencies` and that's what causing this.

I'm going to try to reproduce if this is what really happened with this bug.

**Comment by winter-ice** [comment]
After I checked, the reason in my case is that I use the next version, version 2 works well.

**Comment by tsanyqudsi** [comment]
i'm closing this then
