### ISSUE TITLE
Ring inline style

### ISSUE THREAD

**Issue by AldeonMoriak** [windicss/vite-plugin-windicss#17]
Hello,
I am using this plugin, but when I add ```focus:ring-purple-800``` the purple color doesn't affect the input. I checked it in the in the element section of dev tools and I found out an inline style was set to the input and in there the ring color was blue.
Should I do something to disable the default inline style?
![image](https://user-images.githubusercontent.com/37976890/108108377-cc092c00-70a5-11eb-9604-9e900eb8cb79.png)

**Comment by AldeonMoriak** [comment]
By the way I added windicss plugin after I installed tailwindcss

**Comment by antfu** [comment]
Can you share some code snippets or even better a reproduction? Can't really teal with a screenshot.

**Comment by AldeonMoriak** [comment]
Ok, I created a brand new vite/vue 3 app and added windicss to it. Then I added an input:
```html
 <input
    class="pl-3 pr-3 py-2 w-full bg-white dark:bg-gray-800 text-gray-700 
    dark:text-gray-300 border border-gray-300 
    dark:border-gray-600 rounded-md 
    focus:border-purple-800 dark:focus:border-purple-800 
    focus:outline-none focus:ring-2 focus:ring-gray-800 transition duration-500 ease-in-out"
  />
```
All the other configs are set to default.

**Comment by AldeonMoriak** [comment]
Sorry, but I still can't get a purple ring color. Should I do something else beside updating vite-plugin-windicss?

**Comment by antfu** [comment]
Can you share a reproduction repo?

**Comment by AldeonMoriak** [comment]
The [link](https://github.com/AldeonMoriak/test-vite-windicss) to my repo

**Comment by antfu** [comment]
Variable `--tw-ring-opacity` is missing in the generated css. @voorjaar do you have any idea on this?

**Comment by voorjaar** [comment]
> Variable `--tw-ring-opacity` is missing in the generated css. @voorjaar do you have any idea on this?

https://github.com/windicss/windicss/commit/6993b1713e5e1cd520e8c0468b0346a188d3473b fix this.

**Comment by antfu** [comment]
Thanks! When you release it I will update the deps and close this then.
