### ISSUE TITLE
Applying CSS changes in external folder (inside monorepo) cause delayed change

### ISSUE THREAD

**Issue by ttxtosca** [windicss/vite-plugin-windicss#170]
Hello!

**Describe the bug**
Applying CSS changes in external folder (inside monorepo) cause delayed change (hmr / dev mode). 

**Minimal Reproductions**
~~Sorry, no repro at the moment (using standard yarn-only monorepo).~~
EDIT: made a [repro](https://github.com/ttxtosca/vite-plugin-windicss-issue-170)

**Versions**
- vite-plugin-windicss: 0.15.10
- vite: 2.3.0 (2.2.x mostly may cause same bug)
- framework(vue/react/svelte/etc): vue (latest/current)

**Additonal Context**
Strange bug, maybe not only related to WindiCSS or vite-plugin-windicss themselves, but any change for sfc style (scoped or not) is delayed by "1 change" at each update. Applying update in 'template' or 'script' cause different bug (but not linked - eg. not applyied at all when attribute is changed). But the real deal here is on applying a CSS change, wierd behavior that delay any change **by one step** (only had this bug when using imported component from package inside a monorepo): changes apply, but after one save at each time, or dev server is restarted. Besides that, everything is working fine (tested about all possibilities :)

Checked the network changes in browser, seams everything is fine (scoping /@fs/home... in a linux env). Seams like a Vite issue.

Except that minor problem, congrats for this plugin (windi in general), i'm all for it! Sorry for my rusted english

**Comment by antfu** [comment]
What's your windi.config.js? Have you included those files?

**Comment by ttxtosca** [comment]
I did, they are included and are working (except this delay). Here is the config : 

```js
export default {
	darkMode: false,
	extract: {
		include: [
			'lib/**/*.{vue,html}',
			'../../a/b/lib/**/*.{vue,html}',
		],
	},
};
// Also tried moving config in vite.config.js : 
// ...
		WindiCSS({
			scan: {
				dirs: ['.', '../../a/b/lib'],
				fileExtensions: ['vue', 'js'],
			}
		}),
// ...
```
Lookup is working fine like this with Windi + plugins like 'vite-plugin-components' (eg. simple relative glob).

I gonna try to make a quick repro.

**Comment by ttxtosca** [comment]
Made a [repro](https://github.com/ttxtosca/vite-plugin-windicss-issue-170).

Package @a/sub-a is the main app, @b/sub-b the "external" source. See [this file](https://github.com/ttxtosca/vite-plugin-windicss-issue-170/blob/master/packages/%40b/sub-b/lib/cpn.vue) where bug(s) come from.

By the way the main issue is from changes in the style part of SFC. Except HMR/DevMode, build is working fine.

As a reminder, this is a "yarn-style" monorepo.

**Comment by ttxtosca** [comment]
Solved!

Was not related to windiCSS or vite plugin for windi.

Had to specify option `{server: {watch: {usePolling: true}}}` in vite.config as suggested in [chokidar docs](https://github.com/paulmillr/chokidar#performance).

Anyway, thank you @antfu, continue the great work :) See you
