### ISSUE TITLE
Help me config for nuxtjs

### ISSUE THREAD

**Issue by luyentm** [windicss/vite-plugin-windicss#171]
Thank @antfu  for awesome project.
I have problem about add vite-plugin-windicss with my nuxtjs project.
Docment said that
// main.js
`
import 'virtual:windi.css'
`
I do not know where to put **import 'virtual:windi.css'**
My project already install windicss.
Thank alot.

**Comment by antfu** [comment]
Nuxt with Vite? Have you tried https://github.com/windicss/nuxt-windicss-module?

**Comment by luyentm** [comment]
> Nuxt with Vite? Have you tried https://github.com/windicss/nuxt-windicss-module?

Omg, I don't know that it is Compatible with nuxt-vite.
Thank you alot.
