### ISSUE TITLE
[Enhancement] [Vue, Vite Plugin] When using Attributify mode, windi generate mutiple times css style --> Lag

### ISSUE THREAD

**Issue by harrytran998** [windicss/vite-plugin-windicss#183]
Hope your team can fix it!
![image](https://user-images.githubusercontent.com/24296018/119256640-d0386e80-bbeb-11eb-9f1c-409f86f5a643.png)

**Comment by harrytran998** [comment]
Oops, my bad 😔. When I tried to reproduce this problem, I don't see anything with the monolith project.
Bcs I work on the monorepo project, so I must work-around to scan css with this config!

```
include: [
      path.resolve(__dirname, '**/*.{vue,ts}'),
      'src/**/*.{vue,ts}',
      'components/**/*.{vue,ts}',
      '../../some-project-package/**/**/*.{vue,ts}',
],
```

I think it's the root cause of the problem! I already have [the question](https://github.com/windicss/windicss/issues/275) on `windi issue` about handling CSS in the monorepo, but seem ...
Alternatively, bcs I work on the nested monorepo(have at least 3 classes) --> Might be the approach way to scanning CSS it's a bad idea!

That all! Hope you can clear the problem 😊.

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks

**Comment by harrytran998** [comment]
I don't know why but when I update WindiCss `3.0.9` vs Vite WindiCss `0.16.1` --> Anything works correctly 😊. Thank for the quick answers!
