### ISSUE TITLE
Extends base typescript types for attributify syntax

### ISSUE THREAD

**Issue by vabatta** [windicss/vite-plugin-windicss#185]
**Describe the bug**
Using the new attributify features, base element types throws errors for unknown properties in Typescript.

**Minimal Reproductions**
```svelte
<h1 w:text="2xl">Hey,<br /> welcome back.</h1>
<!-- Type '{ wText: string; }' is not assignable to type 'HTMLProps<HTMLHeadingElement>'. Property 'wText' does not exist on type 'HTMLProps<HTMLHeadingElement>'. -->
```

**Current workaround**
The current workaround works when using the prefix `w` so that only matches the attributes that starts with the prefix used. Investigation could be done to see if this can be dynamically inferred.
```ts
type WindiAttributify = `w${Capitalize<string>}`;

declare namespace svelte.JSX {
	type HTMLProps<T> = {
		[k in WindiAttributify]?: string;
	} &
		HTMLProps<T>;
}
```

**Versions**
- vite-plugin-windicss: `0.16.7`
- vite: `2.3.3`
- framework(vue/react/svelte/etc): `SvelteKit@next`

**Comment by antfu** [comment]
https://github.com/windicss/windicss/pull/322
