### ISSUE TITLE
Preflight explicitly include without turning off dynamic include.

### ISSUE THREAD

**Issue by isakkeyten** [windicss/vite-plugin-windicss#186]
Runtime markdown-to-html won't get picked up in build time and thus not have the preflight css reset for those elements.

Repo with minimal reproduction
https://github.com/isakkeyten/windi-runtime-preflight-repro

**Versions**
"@preact/preset-vite": "^2.0.0",
"vite": "^2.3.5",
"vite-plugin-windicss": "^0.16.7",
"windicss": "^3.0.12"

there is a config called `preflight` which can accept `safelist` but this is the opposite of what's needed. As far as I understand what`preflight safelist` does is it turns off preflight except for those explicitly written `safelist` tags. However, what I would need is to have a way to keep preflight dynamic based on what's in jsx so it's minimal with addition to a list of elements i want to be reset regardless of their inclusion.

Currently a hacky way to achieve this is to have a commented out code with some of the basic markdown tags, they get analysed by windi and still included even tho they won't be rendered (not until later in runtime).

![image](https://user-images.githubusercontent.com/18152578/120341471-2fd30000-c2f7-11eb-95cc-4c89a652096b.png)

![image](https://user-images.githubusercontent.com/18152578/120341503-3792a480-c2f7-11eb-93cd-f0003fd5c3b9.png)

**Comment by antfu** [comment]
I am not sure if I got you correctly. The `safelist` will append to the dynamic scanning and will not turn it off.

**Comment by isakkeyten** [comment]
It seems that my implementation was somehow borked, as the config wasn't doing what it was suppoesd to. Closing this for now. :)
