### ISSUE TITLE
Upgrade from 0.16.7 to 0.17 thru 1.0.1 breaks most styles

### ISSUE THREAD

**Issue by qgates** [windicss/vite-plugin-windicss#192]
On a project I've been using vite-plugin-windicss since 0.14.x up to 0.16.7, upgrading to 0.17 and beyond causes many windicss styles to not load and everything breaks pretty badly. Have had to roll back to 0.16.7 for the time being.

Apologies if I missed a readme somewhere indicating breaking changes and how to fix.

Any idea what might be causing the problem? TIA! 🙂

**Comment by antfu** [comment]
Reproduction please, thanks

**Comment by qgates** [comment]
Not sure if by accident or by design, but upgrading to 1.0.3 released in the last few hours seems to have fixed everything. Thanks!! 🙂👍
