### ISSUE TITLE
When use `<md` or `>md` in class name, it results in a lack of style

### ISSUE THREAD

**Issue by Codpoe** [windicss/vite-plugin-windicss#195]
**Describe the bug**
My code:
```tsx
<div className="<md:bg-dark-400"></div>
```
But the class name is missing in the final css style.

Maybe the problem is in a recently updated `regexQuotedString`. If I change it like this, it won’t be a problem, even if it’s not a perfect solution:
```
/(["'`])((?:\\\1|\\\\|\n|\r|(?!-->|\s\*\/).)*?)\1/mg
```

**Minimal Reproductions**
[A simple project created by `@vitejs/app`](https://github.com/Codpoe/vite-plugin-windicss-bug-reproduce)

**Versions**
- vite-plugin-windicss: 1.0.3
- vite: 2.3.7
- framework: react

**Comment by Soabbar** [comment]
That was a change from the last PR, @antfu 
Is that possible to revert back? It makes variants currently unusable.
What was the reason to change this regex?
