### ISSUE TITLE
setting 'translate-x-full' or other translate related class names does not work.

### ISSUE THREAD

**Issue by samadadi** [windicss/vite-plugin-windicss#197]
**Describe the bug**

setting `translate-x-full` or other translate related class names does not work, but setting same with style attribute works fine. I saw the css output but there is no css property related to this class name. So the problem is either with windicss or the 'vite-plugin-windicss' plugin.

related output: `.translate-x-full {
    --tw-translate-x: 100%;
}`

**Versions**
- vite-plugin-windicss: ^1.0.4
- vite: ^2.3.4
- framework(vue/react/svelte/etc): solid js

**Comment by samadadi** [comment]
I am sorry the problem was that I did not include `transform` class name before. But why is that there is so many unnecessary code for just `transform-x` that includes other transforms that I did not include in my code?

**Comment by antfu** [comment]
This is how tailwind was designed. For the reason behind I'd think it's for have multiple transformations apply to the same element, e.g. `translate-x-full translate-y-1/2`

**Comment by schelmo** [comment]
FYI: the need for transform, filter, and backdrop-filter aren't needed anymore since tailwind 2.0
