### ISSUE TITLE
style loss when build for production

### ISSUE THREAD

**Issue by icksky** [windicss/vite-plugin-windicss#198]
**Describe the bug**

use with element-plus cause the css loss 

**Minimal Reproductions**

[windicss-plugin-demo](https://github.com/icksky/windicss-plugin-demo)
**Versions**
- vite-plugin-windicss: 1.0.4
- vite: 2.3.8
- vue: 3.0.11
- element-plus: 1.0.2-beta.48

related to #130 

![image](https://user-images.githubusercontent.com/13565030/122740107-3c26f900-d2b6-11eb-9886-66ee65fea444.png)

**Comment by schelmo** [comment]
on top of the output you will find the real error:
```
warnings when minifying css:
Missing '}' at 12993:1.
Broken URL 'url(data:image/png;
}
```
in you vite.config.ts this helps:
```js
plugins: [vue(), WindiCSS({
  transformCSS: 'pre'
})],
```
or transformCSS: false
if you won't use `@apply` or other directives in your css

**Comment by hannoeru** [comment]
https://github.com/windicss/windicss/pull/365

Upgrade to latest version of windicss and remove `transformCSS: 'pre'` should works.
