### ISSUE TITLE
relative class missing

### ISSUE THREAD

**Issue by sibbng** [windicss/vite-plugin-windicss#20]
My app described in the https://github.com/windicss/windicss/issues/27 has missing `relative` class in runtime.

This is what I found while searching 'relative' on the browser console. It seems invalid.

![image](https://user-images.githubusercontent.com/19991745/108233294-790c9480-70f8-11eb-8e6b-dcf4f1e512ac.png)

**Comment by antfu** [comment]
What's your html looks like?

**Comment by sibbng** [comment]
Probably that lines causes issue https://github.com/sibbng/sibbng.com/blob/f4349ba62212ac0ffddea08fae5721feea08818c/src/pages/Home.vue#L2-L5
