### ISSUE TITLE
Does the vue template support some special variants?

### ISSUE THREAD

**Issue by jiangmaniu** [windicss/vite-plugin-windicss#201]
On the official website, you can see that you can use [variants](https://windicss.org/utilities/variants.html#desktop-first) with prefix symbols like `Only Screen` and `Desktop First`, these variants Can be used well in `class`. But these special variants seem to be unable to be used with `Attributify Mode` (the vue template cannot be parsed).

I generally use `Attributify Mode` to separate classes of different variants, so that it will be clear at a glance during future maintenance as stated on the official website, so I would like to know this issue, I am in [windicss](https://github.com/windicss/windicss/issues/335) This issue has been raised in the repository.

**Comment by antfu** [comment]
Thanks for bringing this up. Please keep track on the issues under windicss repo.
