### ISSUE TITLE
Property 'text' does not exist on type 'HTMLProps<HTMLHeadingElement>'

### ISSUE THREAD

**Issue by Pitasi** [windicss/vite-plugin-windicss#202]
Hey there. I'm trying the new attributify mode and it works as expected, the only problem is caused by typescript not reconognizing these new properties:

```tsx
<h1 text="green-900">Some heading</h1>
```

reports:

```
Type '{ text: string; }' is not assignable to type 'HTMLProps<HTMLHeadingElement>'.
  Property 'text' does not exist on type 'HTMLProps<HTMLHeadingElement>'.ts(2322)
```

is there anything we can do to type these better?

Thanks!

**Comment by antfu** [comment]
https://github.com/windicss/windicss/pull/322

**Comment by Pitasi** [comment]
Thanks!
