### ISSUE TITLE
Styles for classes not being applied

### ISSUE THREAD

**Issue by jakehamilton** [windicss/vite-plugin-windicss#207]
**Describe the bug**

Hey there! I'm trying to use Windi CSS for the first time via Vite. I've gotten all of the other features working, but for some reason Windi isn't adding styles for applied classes. I do notice that there is one style tag added to the document which contains a few base styles (`windicss layer base`), but nothing else. Additionally, adding/removing classes in the devtools doesn't change things either. Seems like there may be some disconnect in the plugin that's causing this.

**Minimal Reproductions**

There isn't much code here yet so I believe the repo I'm working on will do for a reproduction: https://github.com/jakehamilton/lasersandfeelings

To install and run:

```
# Clone
git clone git@github.com:jakehamilton/lasersandfeelings.git

# Enter project
cd lasersandfeelings

# Install dependencies
npm install

# Start the server in development mode
npm run dev

# Navigate to http://localhost:8080 in your browser to see the app running
```

Particularly interesting code...

Here's where I create the Vite Dev Server with the `vite-plugin-windicss` plugin:  https://github.com/jakehamilton/lasersandfeelings/blob/main/server/vite.js#L27

Here's where I handle SSR: https://github.com/jakehamilton/lasersandfeelings/blob/main/server/vite.js#L54-L81

And both `entry-client` and `entry-server` import `virtual:windi.css`:

https://github.com/jakehamilton/lasersandfeelings/blob/main/client/entry-client.tsx

https://github.com/jakehamilton/lasersandfeelings/blob/main/client/entry-server.tsx

**Versions**
- vite-plugin-windicss: ^1.1.1
- vite: ^2.3.8
- framework(vue/react/svelte/etc): preact

**Additonal Context**

I've not used Windi or Vite much before so I could be doing something wrong. If that's the case then sorry for the ticket! Though I figure things should be working with the way I've hooked them up 🤔

**Comment by jakehamilton** [comment]
Interesting, it looks like manually setting `scan.include` can fix this issue:

```ts
scan: {
	include: [
		path.resolve(__dirname, "..", "client", "**/*.tsx"),
	],
},
```

Not sure why the default doesn't work, but for some reason it's not picking up the files without this change. Unsure if that's expected behavior or a potential bug. If it's not considered a bug then do feel free to close this issue! Otherwise I'll leave it up in case 👍

**Comment by antfu** [comment]
Yeah, this is expected. See https://windicss.org/guide/extractions.html#scanning
