### ISSUE TITLE
Buggy on Vite Multi-page app

### ISSUE THREAD

**Issue by lautiamkok** [windicss/vite-plugin-windicss#208]
It's buggy on the multiple-page app. Following the same pattern from this [page](https://vitejs.dev/guide/build.html#multi-page-app), I have the following structure:

```
├── package.json
├── vite.config.js
├── index.html
├── main.js
└── about
    ├── index.html
    └── about.js
```

In my About page, I have the following code:

```
// about/index/.html
<!doctype html>
<html class="bg-green-500 bg-opacity-50">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite App</title>
  </head>
  <body>
    <h2 class="text-8xl italic text-green-500">About</h2>
    <script type="module" src="about.js"></script>
  </body>
</html>

```

In my `about.js`, I have the following line:

`import 'virtual:windi.css'`

Two bugs:

* I expect to see `bg-green-500 bg-opacity-50` on this page that I applied to the `<HTML>` tag, but none showing up.

* I expect to see `text-8xl italic text-green-500` on the `<h2>` tag, but only `italic` is working, the rest are not.

Why??

The reason the `italic` style shows up is that I have that class applied on my Home page:

```
<!doctype html>
<html class="bg-blue-500 bg-opacity-50">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite App</title>
  </head>
  <body>
    <div id="app">
      <h1 class="p-6 text-xl font-bold text-blue-500">Hello World</h1>
      <button class="
        bg-gradient-to-r from-green-400 to-blue-500
        m-4 px-4 py-3 text-white text-center italic rounded cursor-default
        transition-all duration-400
        hover:rounded-2xl
        dark:(from-teal-400 to-yellow-500)
      ">Preview</button>
    </div>
    <script type="module" src="/main.js"></script>
  </body>
</html>
```

It seems that Windi only works on single-page applications!

I use this same structure uisng Tailwind CSS, all styles on the About page and the Home page are showing up as expected and as what the CSS classes say.

I think this is a serious bug on Windi CSS

**Comment by antfu** [comment]
You will need to configure the scanning target: https://windicss.org/guide/extractions.html#scanning

**Comment by lautiamkok** [comment]
Wonderful. It's not a bug. Just a documentation issue. It can be very helpful to include this in the documentation for multi-page apps:

```
// windi.config.js
import { defineConfig } from 'windicss/helpers'

export default defineConfig({
  // https://windicss.org/guide/extractions.html#scanning
  extract: {
    // accepts globs and file paths relative to project root
    include: [
      'index.html',
      './**/index.html',
      'src/**/*.{vue,html,jsx,tsx}',
    ],
    exclude: [
      'node_modules/**/*',
      '.git/**/*',
    ],
  },
})

```
