### ISSUE TITLE
Ruby on Rails Pug probems

### ISSUE THREAD

**Issue by xxSkyy** [windicss/vite-plugin-windicss#214]
I've got couple of problems with Rails and Windi on Vite
One are that tailwind.config.js / windi.config.js / windi.config.ts configs are not being loaded when running bin/vite de, only settings from vite.config.ts works.

Also I've got problem with pug, `div.bg-white` don't work but `div(class='bg-white')` will work or 
```css
div {
  @apply bg-white;
}
```
also works, I can't figure normal classes to work with pug, I did try setting in vite.config.ts scanning, nothing works.

My config
```js
import { defineConfig } from "vite"
import RubyPlugin from "vite-plugin-ruby"
import WindiCSS from "vite-plugin-windicss"
import vue from "@vitejs/plugin-vue"

export default defineConfig({
  plugins: [
    WindiCSS({
      scan: {
        //////// this one helps but doesn't fix problem
        dirs: ["."], // all files in the cwd
        fileExtensions: ["vue", "js", "ts", "pug"], // also enabled scanning for js/ts
      },
    }),
    RubyPlugin(),
    vue(),
  ],
})

```

also got pug dev dependency installed

**Comment by antfu** [comment]
Can you share a reproduction?

**Comment by xxSkyy** [comment]
> Can you share a reproduction?
To start tailwind.config.js are working, I did somehting wrong with it.

About classes it's about loaded components in main component, classes doesn't load, with windi:devtools they are loaded on change only: https://youtu.be/rAhGMAAZNuM

But without them it doesnt work at all in component, but code moved to app.vue works: https://youtu.be/50ayolGOOTU

Repro code : https://github.com/xxSkyy/windiReproduction

**Comment by antfu** [comment]
The `scan` option is deprecated in favor of the `extract.include` in the config file. In this case, you have both of them configure, which make the `scan` option been ignored. You might want move them to the `extract.include` option instead.

https://github.com/xxSkyy/windiReproduction/blob/5837cd0298daa288fdd2f9923aa29a7b25c769d5/tailwind.config.js#L11

**Comment by xxSkyy** [comment]
> The `scan` option is deprecated in favor of the `extract.include` in the config file. In this case, you have both of them configure, which make the `scan` option been ignored. You might want move them to the `extract.include` option instead.
> 
> https://github.com/xxSkyy/windiReproduction/blob/5837cd0298daa288fdd2f9923aa29a7b25c769d5/tailwind.config.js#L11

I added scan function because  
```json
  extract: {
    include: ["app/frontend/**/*.{vue,html,jsx,tsx,pug}"],
    exclude: ["node_modules/**/*", ".git/**/*"],
  },
```
didn't work. I updated repro code by removing scan and results are the same

**Comment by antfu** [comment]
I am not familiar with ruby, but can you try this:

```ts
  extract: {
    include: ["**/*.{vue,html,jsx,tsx,pug}"],
    exclude: ["node_modules", ".git"],
  },
```

I guess the ruby plugin might change the vite's root by somehow.

**Comment by ElMassimo** [comment]
@xxSkyy Make sure to provide the `root` option to the Windi CSS plugin, as in [these instructions](https://vite-ruby.netlify.app/guide/plugins.html#windi-css), and add the `pug` extension to the `fileExtensions` list.

**Comment by ElMassimo** [comment]
Perhaps it's related to [this regression](https://github.com/ElMassimo/vite-plugin-windicss/commit/4a8014fa2461d15c2f203857f057cba08cfcd2d5). It looks like in the latest version config files are resolved against Vite's root, the user setting is being ignored. Making a PR later today.
