### ISSUE TITLE
Cannot use "!" prefix on @apply of SCSS files

### ISSUE THREAD

**Issue by AndrewBastin** [windicss/vite-plugin-windicss#218]
**Describe the bug**
I tried to use `!bg-black` on an SCSS file and it gave me this error:
```
[plugin:vite:css] expected ";".
  ╷
5 │     @apply !bg-black;
  │            ^
  ╵
  src/App.vue 5:12  root stylesheet
```
I then tried to reproduce it on the example project within this repo and I could reproduce this here as well.
I tried setting `transformCSS` to all the possible options to no avail.

**Minimal Reproductions**
Run the example project in this repo and try this:
``` diff
 <style lang="scss" scoped>
 @screen lg {
   .bar {
-    background: orange;
+    @apply !bg-red;
   }
 }
 </style>
```
Doing just `@apply bg-red;` works fine.

**Versions**
- vite-plugin-windicss: 1.2.7
- vite: 2.4.3
- framework(vue/react/svelte/etc): Vue 3

**Additonal Context**

**Comment by antfu** [comment]
I guess this is something can't be workaround easily, I'd suggest to use `postcss` as the lang tag instead.

```hmtl
 <style lang="postcss" scoped>
 @screen lg {
   .bar {
     @apply !bg-red;
   }
 }
 </style>
```
