### ISSUE TITLE
Problems in vitepress

### ISSUE THREAD

**Issue by zigomir** [windicss/vite-plugin-windicss#22]
Hey,

I'm trying out this plugin in `vitepress` and it doesn't work out of the box.

In development, I first need to make a change to the current `.md` file, once HRM kicks in, it correct applies classes. Same thing has to be done on `Layout.vue` – which is also `vitepress` specific.

More problematic is production build, because no used classes end up in production build's `.css` file.

My question is, was/is this ever intended to work with `vitepress` or not really?

**Comment by antfu** [comment]
You will need to setup

```ts
WindiCSS({
  scan: {
    dirs ['.vitepress', 'pages', 'src'] // folders contains your code to be extract as classes
  }
})
```

**Comment by zigomir** [comment]
Amazing, thanks! :)
