### ISSUE TITLE
grid repeat doesn't work with minmax

### ISSUE THREAD

**Issue by SamyzKhalil** [windicss/vite-plugin-windicss#222]
**Describe the bug**

```
grid-cols-[repeat(4,minmax(100px,1fr))]
```
Doesn't generate any styles,
However, using repeat only or minmax only works as expected.

```
grid-cols-[repeat(4,1fr)]
grid-cols-[minmax(100px,1fr)]
```

**Minimal Reproductions**

```
<div class="grid grid-cols-[repeat(4,minmax(100px,1fr))]">Hi</div>
```
[stackblitz](https://stackblitz.com/edit/node-1rvk99?file=index.html) (npm run dev)

**Versions**
- vite-plugin-windicss: 1.2.7
- vite: 2.4.4
- framework(vue/react/svelte/etc): n/a.

**Additonal Context**
I tried reproducing in [windicss.org/play](https://windicss.org/play.html) but the styles generated just fine,
So I suspect it's a problem related to the vite plugin.

**Comment by antfu** [comment]
Fixed with 89577dbb3491e9398afc86681503536b4573e92b
