### ISSUE TITLE
Pug Support

### ISSUE THREAD

**Issue by cliqer** [windicss/vite-plugin-windicss#23]
Trying to upgrade a pug project and found out that windicss does not support pug class attributes.
Bug or am I missing something?

**Comment by antfu** [comment]
Yeah, we don't support pug yet. Please keep tuned.

**Comment by DeFUCC** [comment]
Yeah! That's a really needed feature! Me too on the waitlist.

**Comment by domsen123** [comment]
I think this is an issue again
