### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by anncwb** [windicss/vite-plugin-windicss#24]
## Description

When I use the plug-in, the package will report an error. Although there was a warning in version 0.2.2, it was still packaged successfully. An error occurred in the 0.3.0 version of the packaging

## Step

1. git clone https://github.com/anncwb/vite-plugin-windicss-bug
2. yarn && yarn build
![image](https://user-images.githubusercontent.com/28132598/108290328-1b954800-71cb-11eb-9aac-c99cfd6001f8.png)

This is only a relatively small project, and it will cause packaging failure in a relatively complex project.

Because I use vditor in my project. It may be the internal css problem, but I can package it normally without the plugin vite-plugin-windicss.

**Comment by anncwb** [comment]
@antfu 
Can this be ignored with exclude？I am trying it

**Comment by antfu** [comment]
Not sure why yet. But can you try with 0.3.1?

**Comment by anncwb** [comment]
ok. I try now

**Comment by anncwb** [comment]
@antfu 

 After upgrading to 0.3.1, the same problem as 0.2.2 appeared. CSS compression warning.

I can be sure that this is not a problem with vite, but with this plugin. It will only appear because of this plugin

![image](https://user-images.githubusercontent.com/28132598/108295490-bf362680-71d2-11eb-9e13-c638a74e4983.png)

**Comment by anncwb** [comment]
I updated the git example, you can pull and install again
