### ISSUE TITLE
@layer components not working on build/production

### ISSUE THREAD

**Issue by adiramardiani** [windicss/vite-plugin-windicss#243]
**Describe the bug**
Currently I working on vue 3 using sass and vite-plugin-windicss
When I use yarn dev the template is working well, but when production `yarn build` my template is broken
After I search it turns out scss file with `@layer components` not build

**Minimal Reproductions**
vite.config.js
```js
plugins: [vue(), WindiCSS()],
```

main.js
```js
import { createApp } from 'vue'
import App from './App.vue'
import './assets/scss/style.scss'
```

/assets/scss/style.scss
```scss
@import "layout/global";
@import "layout/content";
```
/assets/scss/layout/_global.scss (working both yarn dev and yarn build)
```scss
html {
    @apply bg-blue-700;
}
```

/assets/scss/layout/_content.scss (working only for yarn dev)
```scss
@layer components {
   .content {
        @apply min-w-0 min-h-screen bg-red-700;
   }
}
```

**Versions**
- "vue": "^3.2.19"
- "@vitejs/plugin-vue": "^1.9.2"
- "@vue/compiler-sfc": "^3.2.19"
- "sass": "^1.42.1"
- "sass-loader": "^12.1.0"
- "vite": "^2.5.10"
- "vite-plugin-windicss": "^1.4.7"
- "windicss": "^3.1.8"

**Additonal Context**
I don't know where is the problem, is the bug or I have some error on code, but before I update dependencies to this version everything works normally (I forgot which version is working fine)

**Comment by cawa-93** [comment]
It also relevant without Vue. You can use my repo to reproduce: https://github.com/cawa-93/windicss-issue

1. `npm run build`
2. `npm run serve`

You should see two same paragraphs with white text on blue background

**Comment by adiramardiani** [comment]
Hi @cawa-93 

Do you have temporary solution for this ?
This serious problem for me when production :(

**Comment by antfu** [comment]
@cawa-93 by default, `vite-plugin-windicss` only scans files under `src`, to make your repro work, you need to specify them in your `windi.config.ts`

```ts
import {defineConfig} from 'windicss/helpers';

export default defineConfig({
  preflight: false,
  extract: {
    include: ['index.css', 'index.html']
  }
});
```

**Comment by cawa-93** [comment]
@antfu So CSS files **also** need to be specified in the extract? It was not obvious to me 😅 That's fix. Thank

**Comment by antfu** [comment]
Yes, giving the fact that you are "extracting" the layers from them to another entry, we will need to scan them statically before the bundling (since there is no HMR in the build). By default, it will include css if you are working under `src` folder.

**Comment by adiramardiani** [comment]
I'm sorry @antfu 
This issue is created by me, this issue is about @layer components, I haven't got the solution and why is it closed ?

Thanks

**Comment by antfu** [comment]
Giving you didn't provide the reproduction I would expect you have the same situation as the one given. You might want to include your assets dir to the extract target.

**Comment by adiramardiani** [comment]
@antfu 

Hmm, do you read my first thread first ?
All issue/ticketing template follow up and every section I describe my problem, you can read on my minimal reproduction

Again, this ticket is about @layer component not working, not about "assets dir to the extract target" because it's written in @cawa-93 problem, and my problem it's different, @cawa-93 just comment on my issue because maybe the problem is same

I have included all assets in the src, but because I said earlier this is the directory of vite, so I assume you understand when I write ./asset it means it is in the src folder

Let me write again with /src, because you always talk about asset dir, and I dont write about "asset dir" in this issue, I write on dev is running, but on production @layer component not working. All style is scan very well on dev, but on production just @layer component is not included on generated build

Please, I just need help, because current this issue show on production, and I have many problem because of it

**Describe the bug**
Currently I working on vue 3 using sass and vite-plugin-windicss
When I use yarn dev the template is working well, but when production `yarn build` my template is broken
After I search it turns out scss file with `@layer components` not build

**Minimal Reproductions**
vite.config.js
```js
plugins: [vue(), WindiCSS()],
```

src/main.js
```js
import { createApp } from 'vue'
import App from './App.vue'
import './assets/scss/style.scss'
```

src/assets/scss/style.scss
```scss
@import "layout/global";
@import "layout/content";
```
src/assets/scss/layout/_global.scss (working both yarn dev and yarn build)
```scss
html {
    @apply bg-blue-700;
}
```

src/assets/scss/layout/_content.scss (working only for yarn dev)
```scss
@layer components {
   .content {
        @apply min-w-0 min-h-screen bg-red-700;
   }
}
```

**Versions**
- "vue": "^3.2.19"
- "@vitejs/plugin-vue": "^1.9.2"
- "@vue/compiler-sfc": "^3.2.19"
- "sass": "^1.42.1"
- "sass-loader": "^12.1.0"
- "vite": "^2.5.10"
- "vite-plugin-windicss": "^1.4.7"
- "windicss": "^3.1.8"

**Additonal Context**
I don't know where is the problem, is the bug or I have some error on code, but before I update dependencies to this version everything works normally (I forgot which version is working fine)

**Comment by antfu** [comment]
I appreciate the info you have provided but sorry this is **NOT** a reproduction

> You can use my repo to reproduce: https://github.com/cawa-93/windicss-issue

This is.

It's still not clear what's your config, what your setup, and I can't be sure if it's a bug or just misconfigure from the info you have provided. Please note you are asking for help for FREE, while I am still willing to help as I could, but aware that my time is also limited. If you don't bother to set up a minimal reproduction environment, you can't expect me to waste 30 minutes following the steps you describe and maybe find it's a non-problem.
