### ISSUE TITLE
Variant groups not working

### ISSUE THREAD

**Issue by rompetomp** [windicss/vite-plugin-windicss#245]
Hi

I started using Windi CSS today, and I'm using the vite plugin.
Input:
```html
<button class="hover:(text-white bg-blue-800) bg-blue-300 font-bold py-2 px-5 rounded">
    Test
</button>
```

Expected output:
```html
<button class="hover:text-white hover:bg-blue-800 bg-blue-300 font-bold py-2 px-5 rounded">
    Test
</button>
```

Effective output: 
```html
<button class="hover:(text-white bg-blue-800) bg-blue-300 font-bold py-2 px-5 rounded">
    Test
</button>
```

As you can see, the hover group is not getting transformed to the normal kind of variants.
I'm using WindiCSS v3.1.9, with vite-plugin-windicss v1.4.9.

This is my windi.config.ts:
```typescript
import { defineConfig } from 'windicss/helpers'

export default defineConfig({
  extract: {
    include: ['resources/views/**/*.blade.php']
  }
})
```

Thanks in advance

**Comment by rompetomp** [comment]
My bad, I think I misunderstood what this package is meant to do. I wanted to integrate Windi CSS with Laravel / Blade. Seems like this currently only works with frontend frameworks (because it needs to change the classes rendered in the HTML), am I correct in assuming this?

**Comment by antfu** [comment]
Yes, unfortunately, variant groups is relaying code transformation. I would recommend [attribuitify mode](https://windicss.org/posts/v30.html#attributify-mode) which provide similar features without code transform.

**Comment by codyzu** [comment]
I realized this is also the case with the CLI... I may suggest an edit in the docs.
