### ISSUE TITLE
devtools: MutationObserver is not defined in SSR

### ISSUE THREAD

**Issue by mrwokkel** [windicss/vite-plugin-windicss#247]
**Describe the bug**
When using the windi devtools and starting op a dev server, I get the error:

> [vite] Error when evaluating SSR module /@windicss/devtools:
ReferenceError: MutationObserver is not defined

**Minimal Reproductions**
https://github.com/mrwokkel/mutationobserver

**Versions**
- vite-plugin-windicss: ^1.4.11
- vite: ^2.6.7
- framework: @sveltejs/kit

**Additonal Context**
When loading virtual:windi-devtools in browser only, it works. But seems that should check on existence of MutationObserver before even starting.

**Comment by antfu** [comment]
What's the browser you are using?

**Comment by mrwokkel** [comment]
Problem is the Server Side Rendering part...
