### ISSUE TITLE
`attributify` is not working with space separated values

### ISSUE THREAD

**Issue by Hrishikesh-K** [windicss/vite-plugin-windicss#256]
**Describe the bug:**

I'm trying to get started with Windi CSS (Vite + Vue 3). I'm looking forward to use `attributify`. I spent hours trying to figure out why it wasn't working, until I realised, it works when I do this:

```vue
<div h="20"></div>
```

instead of

```vue
<div h = "20"></div>
```

This wasn't obvious to me as I usually keep spaces between attribute name, the equal sign and the value itself. Also, the [documentation](https://windicss.org/posts/attributify.html) uses it that way: 

![image](https://user-images.githubusercontent.com/11403551/143575176-448e5184-6cc1-4d6c-b1ae-d201b842d1b8.png)

This could be something wrong with my setup too, but it doesn't seem so at the moment. But, please let me know if that's the case.

**Minimal reproduction:**

Here's a zip of a primitive reproduction of my use case: [test.zip](https://github.com/windicss/vite-plugin-windicss/files/7608549/test.zip)

**Versions:**

- vite-plugin-windicss: 1.5.1
- vite: 2.6.14
- vue: 3.2.22

**Additional context:**

I noticed that, if I have used the same attribute like:

```vue
<div h="20"></div>
<div h = "20"></div>
```

it works for both of those as it probably detects the first one and thus, generates the style that applies for the other one too.

However, if I use it like:

```vue
<div h="20"></div>
<div h = "40"></div>
```

there's no style generated for the second one.

**Comment by antfu** [comment]
The documentation is probably a mistake. Actually, this is my first time to see that you can use the syntax with spaces. I generally not going to recommend that usage, but if you really want it, PR welcome (it should be a straghtforward regex update)

**Comment by Hrishikesh-K** [comment]
Sure thing, I'll give this a go this weekend or so. Just to confirm, this looks like a file that needs to be changed, correct: https://github.com/windicss/vite-plugin-windicss/blob/main/packages/plugin-utils/src/regexes.ts?

Also, it's not an issue specific to Windi CSS. Vetur also had this problem where it was me again to report it: https://github.com/vuejs/vetur/issues/3133.

Maybe I should train my eyes to ignore the lack of space.

**Comment by Hrishikesh-K** [comment]
Opened a PR: https://github.com/windicss/vite-plugin-windicss/pull/257.

**Comment by eugenesvk** [comment]
Would it be possible to add **multiple spaces** to the regex as I believe that the vertically-aligned
```
  bg     = "blue-400 hover:blue-500 dark:blue-500 dark:hover:blue-600"
  text   = "sm white"
  font   = "mono light"
  p      = "y-2 x-4"
  border = "2 rounded blue-200"
```
is much more readable vs the non-vertically-aligned
```
  bg="blue-400 hover:blue-500 dark:blue-500 dark:hover:blue-600"
  text="sm white"
  font="mono light"
  p="y-2 x-4"
  border="2 rounded blue-200"
```
