### ISSUE TITLE
Issue with VitePress running from subdirectory

### ISSUE THREAD

**Issue by ky-is** [windicss/vite-plugin-windicss#26]
This plugin works great for me with VitePress when the `.vitepress` folder is in the project root. But when I place it in a subdirectory (i.e. `docs/`), it fails to find the generated `windi.css` import file. Not sure if there's a config change I'm missing here?

Repro: https://github.com/ky-is/vite-plugin-windicss-vitepress-bug

Thanks for the awesome project!

**Comment by antfu** [comment]
See #22

**Comment by ky-is** [comment]
Thanks @antfu, but I don't think these issues are related. This is an import failure that prevents the app from running with: `[vite] Internal server error: Failed to resolve import "windi.css". Does the file exist?` but only when `.vitepress` is placed in a subdirectory.

Please check out the sample repo when you have a chance.

**Comment by antfu** [comment]
@ky-is you will need to move the `vite.config.js` file into `docs` I think

**Comment by ky-is** [comment]
Awesome that does it, thanks for helping me through this. I kept trying to change the `root` option in the config itself and getting stuck. Gonna read through their docs again later and see what I missed.
