### ISSUE TITLE
Fetch failed loading: POST "http://localhost:4000/@windicss-devtools-update".

### ISSUE THREAD

**Issue by tomoat** [windicss/vite-plugin-windicss#285]
**Describe the bug**

**Minimal Reproductions**

**Versions**
- vite-plugin-windicss: 1.8.2
- vite: 2.8.6
- framework(vue/react/svelte/etc):  vue

**Additonal Context**

<img width="668" alt="image" src="https://user-images.githubusercontent.com/7428698/156690288-9ec29cc2-4542-49b3-8dae-e39da47f31ab.png">

<img width="838" alt="image" src="https://user-images.githubusercontent.com/7428698/156690436-30b29005-8ff2-4064-85c2-a8bed284be9d.png">

**Comment by await-ovo** [comment]
Can you provide a repository and steps that can be reproduced, I am interested in this problem, but I have not succeeded in reproducing it on my side.

**Comment by tomoat** [comment]
@await-ovo   https://github.com/tomoat/vite-app
