### ISSUE TITLE
hmr causes memory overflow

### ISSUE THREAD

**Issue by anncwb** [windicss/vite-plugin-windicss#30]
I'm sorry that I can't provide a recurring example for this problem, because this problem happened by accident

## description:

After I modify the components, hmr is very slow and the browser cannot be refreshed. After a while, the browser freezes

This happened by accident. I used it yesterday 3 times in total, but I didn't find any error messages. I had to re-execute `yarn dev` to solve it.

I raised this question, mainly because you may know which aspect of the problem, I will continue to follow up this problem

**Comment by anncwb** [comment]
I also feel that hmr takes about 3-5 seconds to take effect in medium-scale projects

**Comment by anncwb** [comment]
![image](https://user-images.githubusercontent.com/28132598/108579631-d3a92900-7362-11eb-908d-1926e46b680b.png)
Is the information on the console as well as I misunderstood it? Every time hmr is executed, there will be one
?

I see the above information is from x2 .... x8. This is not the same message, because the above is printed [vite] hmr update /@windicss/windi.css

**Comment by anncwb** [comment]
https://github.com/windicss/vite-plugin-windicss/blob/1d8633d92d1f7039cc8c733331f5c3e076fea393/packages/vite-plugin-windicss/src/index.ts#L68

```ts
const fileContent=cache.get(file)
if(file === utils.configFilePath&&fileContent!==getFileContent(file)){
//xxx
}

```


Can a cache be added to this location? When you press `ctrl+s` continuously in vscode, hmr will be triggered, but the content of the file has not changed at this time

As shown in the figure below, if I press Save several times in a row, the page refresh will be triggered. But the content of the file has not changed

![image](https://user-images.githubusercontent.com/28132598/108580096-f9373200-7364-11eb-9db6-24ebe9793395.png)

**Comment by antfu** [comment]
> if (file === utils.configFilePath) { 

Looks like you are changing `main.ts`? Which I don't think will trigger a full reload (at least by this plugin)

> x2 .... x8

It's not clear to me how many times you have saved the files. If a repro is not appliable, can you maybe share a video clip for that? Thanks!

**Comment by anncwb** [comment]
This file is not changed, just press ctrl+s

https://vebn.oss-cn-beijing.aliyuncs.com/upload/Kapture%202021-02-20%20at%2013.21.16.gif

**Comment by anncwb** [comment]
@antfu 

I also found a possible cause of this problem. for reference only:

In the actual project, create a vue file, even if this file is not used, it will trigger hmr and cause the page to reload. I think this should not be expected
