### ISSUE TITLE
hmr question

### ISSUE THREAD

**Issue by anncwb** [windicss/vite-plugin-windicss#31]
First of all, this project is great. But I still have some questions about hMR

## step

- git clone https://github.com/anncwb/vite-plugin-windicss-bug
- yarn && yarn dev
- Open the project in vscode and find /src/main.ts. Press ctrl+s several times in a row

A log appeared. Is this triggered multiple times?

Secondly, open app.vue in the same way and press save continuously, the following situation will also occur. Even if the content is changed, (x...) is still incremented

![image](https://user-images.githubusercontent.com/28132598/108589870-93b26800-739b-11eb-9fcd-08ad3d2649f1.png)

![image](https://user-images.githubusercontent.com/28132598/108589930-e0963e80-739b-11eb-9a7b-02440e5b2eef.png)

I just opened a question about memory overflow. https://github.com/windicss/vite-plugin-windicss/issues/30
 As I didn’t reproduce it again, but something happened to my colleague

![image](https://user-images.githubusercontent.com/28132598/108590030-5f8b7700-739c-11eb-8230-4125f6495a5b.png)

Its operation is only continuous hot update and then the memory overflows. So I wonder if the hot update can be optimized again?

It stands to reason that the content of the same file has not changed. Save should not trigger a hot update. 

###  Finally, this project has another hot update issue

- Open A.vue in the editor and save the file. Hot update is triggered.

But this project did not use A.vue, why would it trigger hmr? Is this also a point that may cause memory overflow

![image](https://user-images.githubusercontent.com/28132598/108590120-d0cb2a00-739c-11eb-8ab8-e34a2a119945.png)

@antfu  Can you answer me？thank you！

**Comment by antfu** [comment]
> Secondly, open app.vue in the same way and press save continuously, the following situation will also occur. Even if the content is changed, (x...) is still incremented

This is not related to this plugin. You can try to comment out the plugin and try again.

> A.vue

I will have a look

**Comment by anncwb** [comment]
> > Secondly, open app.vue in the same way and press save continuously, the following situation will also occur. Even if the content is changed, (x...) is still incremented
> 
> This is not related to this plugin. You can try to comment out the plugin and try again.
> 
> > A.vue
> 
> I will have a look

I tried to annotate the plugin. Press save in main.ts, it will still appear. So this may be a problem with vite. I will go to Vite to open an issue.

But the App.vue file disappeared after commenting out the plugin. So I think it might be the same problem as A.vue
