### ISSUE TITLE
Upgrade to use Windicss v3.4.2

### ISSUE THREAD

**Issue by vexkiddy** [windicss/vite-plugin-windicss#323]
Hiya, 

I'm using Sveltekit and really need to access the 'content' upgrades in v3.4.2. Would it be possible to upgrade the version of WindiCSS this uses ? Currently its running v3.

Many thanks!

**Comment by antfu** [comment]
You can use bump it in your local lockfile, it's in semver range

**Comment by vexkiddy** [comment]
hiya.. thanks for this, but i have no idea how to do this.. :(

**Comment by antfu** [comment]
It's actually already 3.5.6: https://github.com/windicss/vite-plugin-windicss/blob/main/package.json#L50

**Comment by vexkiddy** [comment]
thanks @antfu, also checked the package.json and you're correct. curious why then that the features in v3.4 don't work ?
