### ISSUE TITLE
Apply directive has no effect on Windows

### ISSUE THREAD

**Issue by jpwain** [windicss/vite-plugin-windicss#34]
I'm trying out Vite + Windi CSS and it seems to work other than my `@apply` directive not having any effect.

[Here's the file](https://github.com/jpwain/testo/blob/main/index.html) with my directive in the `<style>` block. Rendered output is like this: 

![Xnip2021-02-20_12-17-38](https://user-images.githubusercontent.com/1234304/108607508-a4e87e00-7375-11eb-8edb-0f59d82cf8f7.png)

Is there further configuration needed, such as which CSS should be compiled, or some place I need to locate directives?

**Comment by antfu** [comment]
It does work for index.html, you will need to move it to a separate CSS file and import it.

**Comment by jpwain** [comment]
I separated my CSS [into a separate file](https://github.com/jpwain/testo/blob/main/style.css) and tried these:

* [linking to the file](https://github.com/jpwain/testo/blob/a98c59c42b05e9596b953c567b162eaec9b188ad/index.html#L6)  from the page `<head>`
* [using `@import`](https://github.com/jpwain/testo/blob/a98c59c42b05e9596b953c567b162eaec9b188ad/index.html#L9)  in a `<style>` block in the `<head>`
* [importing from main.js](https://github.com/jpwain/testo/blob/a98c59c42b05e9596b953c567b162eaec9b188ad/main.js#L2)

None of these approaches are making my `@apply` directive work. What am I doing wrong?

**Comment by antfu** [comment]
Just pull down your code and fired up without any changes, I think it works as expected.

![image](https://user-images.githubusercontent.com/11247099/108634991-a15d1000-74b7-11eb-8d61-13ff17c84291.png)

**Comment by jpwain** [comment]
I switched to a different machine, pulled the repo down, fired it up, and it still doesn't work. 🤷   I'm going to start a fresh new Vite project and see if that changes anything for me.

**Comment by antfu** [comment]
Can you run `DEBUG=vite-plugin-windicss:* npm run dev` and share the logs with me? Thanks

**Comment by jpwain** [comment]
Here you go:
```shell
❯ DEBUG=vite-plugin-windicss:* npm run dev

> testo@0.0.0 dev
> vite

  vite-plugin-windicss:glob globs [ 'index.html', 'src/**/*.{html,vue,md,pug,jsx,tsx,svelte}' ] +0ms
  vite-plugin-windicss:config {} +0ms

 ⚡ Vite dev server running at:

  > Local:    http://localhost:3000/
  > Network:  http://192.168.86.24:3000/

  ready in 124ms.

  vite-plugin-windicss:glob files [ '/Users/jpwain/git/testo/index.html' ] +1s
  vite-plugin-windicss:detect classes Set(13) {
  'en',
  'viewport',
  'stylesheet',
  'text/css',
  'style.css',
  'prose-lg',
  'app',
  'module',
  'bg-pink-200',
  'p-4',
  'text-xl',
  'cooldiv',
  'text-sm'
} +0ms
  vite-plugin-windicss:detect tags Set(9) {
  'html',
  'body',
  'div',
  'head',
  'meta',
  'link',
  'title',
  'style',
  'script'
} +0ms
  vite-plugin-windicss:compile compiled 4 classes +0ms
  vite-plugin-windicss:compile [ 'bg-pink-200', 'p-4', 'text-xl', 'text-sm' ] +0ms
  vite-plugin-windicss:transform:css /@windicss/windi.css +0ms
```

**Comment by antfu** [comment]
Sorry, I still can not repro it, you can have a look at your browser console to see if anything been blocked?

**Comment by bux** [comment]
I've encountered the same/similar issue.

Repro: https://bitbucket.org/kh-JDA/crguide-vue3/src/windi/

**Comment by antfu** [comment]
@bux you didn't have WindiCSS setup properly, please read the guide in README.

**Comment by bux** [comment]
@antfu I've read and applied all in the guide to the letter (except for removing the postcss config because I use postcss-nested)
Changes: https://bitbucket.org/kh-JDA/crguide-vue3/commits/22ca0bcdc9308b8c8a07523c2837e0817c70ba45

But still apply is not working unfortunately.

**Comment by antfu** [comment]
@bux I can see it's applied
![image](https://user-images.githubusercontent.com/11247099/108828315-a928cb80-7601-11eb-8368-10f673e4ab1e.png)

**Comment by bux** [comment]
@antfu I can't get it to work. I tried deleting and reinstalling "node_modules". No success.
I also checked if maybe building it on windows could have been a problem and used a wsl2 debian distro but even there "apply" is not applied.

I now will try it with a fresh vite install.

**Comment by bux** [comment]
@antfu even on a fresh vite install apply is not getting applied. I even tried switching to node v15.9.0.

Fresh vite install test repo: https://github.com/bux/windi-test

Do you want me to test something in particular?

**Comment by antfu** [comment]
@bux Is this expected?
![image](https://user-images.githubusercontent.com/11247099/108835422-68818000-760a-11eb-8f7a-87127ba9c411.png)

**Comment by antfu** [comment]
Maybe you can show me the logs you have with `vite --debug`

**Comment by bux** [comment]
[vite-debug.log](https://github.com/windicss/vite-plugin-windicss/files/6028600/vite-debug.log)

[vite-plugin-windicss.debug.log](https://github.com/windicss/vite-plugin-windicss/files/6028615/vite-plugin-windicss.debug.log)

I hope this helps.

**Comment by bux** [comment]
@antfu I tried with v0.4.9 but the problem still occurs. 

>I can't repro on my side

yeah, I know, that's a mighty annoying situation for every dev 😄

**Comment by bux** [comment]
Still happens on v0.9.4 sadly.

**Comment by antfu** [comment]
We have tested out on Windows, but we still can not reproduce it. Can you try with the latest version and provide the log of `DEBUG=vite-plugin-windicss:* vite` with it again. Thank you!

**Comment by bux** [comment]
@antfu Testing with v0.10.2 but still @apply is not being "applied".

![image](https://user-images.githubusercontent.com/1235520/112634544-04392280-8e3b-11eb-9fc7-95fedb07b013.png)

**Comment by bux** [comment]
I can't reproduce this anymore with v0.15.10 and node v14.17.0.

**Comment by antfu** [comment]
That's great!
