### ISSUE TITLE
Set typescript alias options got an error

### ISSUE THREAD

**Issue by ShareManT** [windicss/vite-plugin-windicss#40]
When I add the typescript alias and baseUrl options to tsconfig.json, I failed to run my project.
![image](https://user-images.githubusercontent.com/4065724/108650204-fcaff200-74f9-11eb-8340-a5b151492f4c.png)

The error details:
![image](https://user-images.githubusercontent.com/4065724/108650214-06d1f080-74fa-11eb-8e59-f90e5b556229.png)

I can run project successfuly, when I tried to remove the alias and baseUrl options at tsconfig.json.

Thanks for dudes' helping!

**Comment by antfu** [comment]
Make sure `tsconfig.json` is a valid JSON, this is where esbuild-register requires.

**Comment by ShareManT** [comment]
> Make sure `tsconfig.json` is a valid JSON, this is where esbuild-register requires.

Thank for your rapid reply!

Actually I don't know about the `esbuild-register` package.

I post my `tsconfig.json` below :
`json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": [
      "esnext",
      "dom"
    ],
    "types": [
      "vite/client",
      "node"
    ],
    "baseUrl": "./",
    "paths": {
      "/@/*": ["./src/*"],
      "/@components/*": ["./src/components/*"],
      "/@views/*": ["./src/views/*"],
      "/@plugins/*": ["./src/plugins/*"],
    }
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue"
  ]
}
`

**Comment by antfu** [comment]
```diff
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": [
      "esnext",
      "dom"
    ],
    "types": [
      "vite/client",
      "node"
    ],
    "baseUrl": "./",
    "paths": {
      "/@/*": ["./src/*"],
      "/@components/*": ["./src/components/*"],
      "/@views/*": ["./src/views/*"],
-      "/@plugins/*": ["./src/plugins/*"],
+      "/@plugins/*": ["./src/plugins/*"]
    }
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue"
  ]
}
```
