### ISSUE TITLE
Styles not scoped within @screen directive

### ISSUE THREAD

**Issue by nicooprat** [windicss/vite-plugin-windicss#41]
Hi there,

These styles:

```html
<style scoped>
nav {
 background: blue;
}

@screen md {
  nav {
    background: blue;
  }
}
</style>
```

are compiled to:

```html
<style type="text/css">
nav[data-v-264bddce] {
  background: blue;
}
@media (min-width: 768px) {
  nav {
    background: blue;
  }
}
</style>
```

It's supposed to be compiled to:

```html
<style type="text/css">
nav[data-v-264bddce] {
  background: blue;
}
@media (min-width: 768px) {
  nav[data-v-264bddce] {
    background: blue;
  }
}
</style>
```

Never encountered this bug with Tailwind + vue-cli, so I thought it should belong here. Using standard media queries instead of `@screen` directive still works.

Thanks for your work!

**Comment by antfu** [comment]
With v0.4.6, you can make it work by 

```ts
WindiCSS({
  transformCSS: 'pre'
})
```

Sorry, I can't make it default as it will break other processors like Sass and Stylus.

**Comment by nicooprat** [comment]
That was quick! Just tested it, it works, thanks 🙏
