### ISSUE TITLE
[Bug] @apply variant won't work in react project with less css preprocessor enabled.

### ISSUE THREAD

**Issue by Ynewtime** [windicss/vite-plugin-windicss#45]
## Bug description

`@apply` variant won't work in `react` project with `less` css preprocessor enabled.

## How to reproduce

check reproduction repo: https://github.com/Ynewtime/vite-react-ts-with-less

1. `yarn create @vitejs/app`
2. `yarn install -D less`
3. follow the install guide of https://github.com/windicss/vite-plugin-windicss#install
4. change `src/App.css` to `App.less` and add `test` class with `@apply` variant
5. use `test` class in `src/App.tsx`

## More information

I've tested with `sass` and `postcss-nesting`, both work well with `@apply` variant, it seems just `less` could not.

**Comment by antfu** [comment]
Yeah, sorry I totally forget about less. It would work with v0.4.11 now.
