### ISSUE TITLE
[Bug]Nesting feature of less no more working

### ISSUE THREAD

**Issue by Ynewtime** [windicss/vite-plugin-windicss#46]
## Bug description

[Nesting feature](http://lesscss.org/#nesting) of less no more working

## How to reproduce

check reproduction repo: https://github.com/Ynewtime/vite-react-ts-with-less

1. `yarn create @vitejs/app`
2. `yarn install -D less`
3. follow the install guide of https://github.com/windicss/vite-plugin-windicss#install
4. change `src/App.css` to `App.less` and add some `less` css to it, like these:

```less
.parent {
  color: red;

  .child {
    color: red;
  }
}
```

5. use `parent` and `child` class in `src/App.tsx`

## More information

If this plugin was disabled, the nesting feature would work.

**Comment by anncwb** [comment]
After my project was upgraded to 4.1.1, all the less reported errors
