### ISSUE TITLE
use iconfont error

### ISSUE THREAD

**Issue by PingTouG** [windicss/vite-plugin-windicss#49]
### Version
^0.4.7

`vite`: ^2.0.2

### Reproduction link
https://github.com/PingTouG/vite-iconfont

### Steps to reproduce
Just run it.

### What is expected?
Use `vite-plugin-windicss`, iconfont can work.

### What is actually happening?
If use `vite-plugin-windicss`, iconfont can't work.

**Comment by antfu** [comment]
Fixed in windicss/windicss#106
