### ISSUE TITLE
Source maps not created for all files containing tailwind/windicss styles with vite build when sourcemap setting is set

### ISSUE THREAD

**Issue by gunters63** [windicss/vite-plugin-windicss#52]
Hi there,

first thanks for Windicss and the vite plugin, makes frontend development is joyful again :)

I switched my project now from create-react-app and TailwindCSS over to vite and windicss. It was a very smooth switch so far.

One little thing I noticed: I added sourcemaps to the build (vite.config: build: {sourcemap: true}} because i like sometimes to debug a production build. The build gives me a lot of warnings:

````
Sourcemap is likely to be incorrect: a plugin (vite-plugin-windicss:groups) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
````

As this affects only CSS and I really don't need sourcemaps for them I can ignore these warnings. But is there a way to disable them in the first place?

Thanks

**Comment by gunters63** [comment]
It seems I was not correct.

Some source maps are still created correctly (all *.ts and *.js files), but sourcemaps for .tsx files are completely missing.
They were generated correctly when I used tailwindcss together with vite so it seems the warning above not only relates to source maps for CSS files.

**Comment by gunters63** [comment]
The problem should easily be reproducable by setting {build: {sourcemap: true}} in any project using the plugin which has *.tsx (and likely *.jsx) files and executing a vite build.

**Comment by gunters63** [comment]
I found a workaround for now. As I don't really need the feature to transform groups (Transform groups like `hover:(bg-gray-100 font-medium)`) i disabled the feature in the vite.config.file section for WindiCSS now:

````
 WindiCSS({
      safelist: 'prose prose-sm m-auto',
      transformGroups: false,
    }),
````

and got sourcemaps back for my tsx files :).

By the way, it was not the .tsx files affected, but any file containing tailwind/windicss styles.

**Comment by antfu** [comment]
Source map supported

**Comment by gunters63** [comment]
Source maps generated from build work now for me, thank you :)
