### ISSUE TITLE
  Some color classes don't work

### ISSUE THREAD

**Issue by yangss3** [windicss/vite-plugin-windicss#56]
I remember it was ok a few days ago, but today I create a new project , the following code doesn't work any more

 vite.config.ts
```
//...
import WindiCSS from 'vite-plugin-windicss'
export default defineConfig({
   //...
   WindiCSS(),
})
```
main.ts
```ts
import 'windi.css'
```
App.vue
```html
<h1 class="bg-teal-500 text-orange-500">hello</h1>
```

**Comment by antfu** [comment]
Can you share a minial repro? Thanks.

**Comment by yangss3** [comment]
https://github.com/yangss3/vite-windi-test.git
You can try it, thank you

**Comment by yangss3** [comment]
I think it's the WindiCSS itself, because the WindiCSS IntelliSense extension also doesn't work on those class today, and I found its version updated a few hours ago, maybe WindCSS removed these classes

**Comment by antfu** [comment]
It's introduced here
https://github.com/windicss/windicss/commit/49c57f44d0658a0fbada69797d797e720ec03f2c

You can either revert back to v2.2.1 for now, or configure those colors explicitly in the config.

/cc @voorjaar wondering why these colors get removed by default. To me, enabling all colors by default is a huge plus for me comparing Tailwind.

**Comment by voorjaar** [comment]
What I thought before was that deleting some colors might improve the efficiency of the vscode extension. Since it is still used, I think I can restore this in the next version.

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss/commit/04f2193bed83c52465507ff0fb705d4134eceab8 revert it.

**Comment by antfu** [comment]
Should be fixed in the latest version.

**Comment by yangss3** [comment]
Thanks
