### ISSUE TITLE
Vite doesn't pick up on changes to tailwind.config.ts?

### ISSUE THREAD

**Issue by HerbCaudill** [windicss/vite-plugin-windicss#57]
### To reproduce: 

Clone this repo: https://github.com/HerbCaudill/hello-vite  

      yarn install  
      yarn dev 

Note that background color is violet.

Open `tailwind.config.ts` and change the primary color from `violet` to `blue`:

      primary: colors.blue,

### Actual behavior

- In the terminal: Vite doesn't react to the change
- In the browser: the background color doesn't change

The only way to get the change to register is to restart the dev server (or touch `vite.config.ts`, which I guess triggers a complete rebuild.)

### Desired behavior

The browser updates immediately, just as it would if I modified the `className` directly in `App.tsx`.

### Notes

[This PR](https://github.com/vitejs/vite/pull/408) referencing [this issue](https://github.com/vitejs/vite/issues/293) in the Vite repo suggests that this problem was noted and fixed in Vite at some point.

**Comment by antfu** [comment]
![image](https://user-images.githubusercontent.com/11247099/109665654-5d4dc780-7ba9-11eb-9cfc-82f9eb17448a.png)

Do you see this on your console?

**Comment by antfu** [comment]
https://user-images.githubusercontent.com/11247099/109666133-de0cc380-7ba9-11eb-8f33-95a9114c3552.mov

Your repo works for me

**Comment by HerbCaudill** [comment]
> Do you see this on your console?

No, when I save, nothing at all happens. 

Very weird that it works on your box. I'm on Windows, wonder if that's it?￼

**Comment by HerbCaudill** [comment]
sweet, that did the trick - thanks!!
