### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by anncwb** [windicss/vite-plugin-windicss#58]
Sorry that this question cannot be reproduced. I mentioned a memory issue before https://github.com/windicss/vite-plugin-windicss/issues/30.

At that time, you repaired it, and the frequency of appearance was reduced a lot. I received a lot of feedback that it was stuck when Vite was performing a hot update, and it would cause the hot update to be incorrect.

Mainly manifested in the following points:
1. When the hot update is triggered continuously, the page refresh time is obviously longer. When the hot update reaches a certain amount, refresh the interface. At this time, the interface may take a long time to refresh, which may cause memory overflow on some computers.
2. After the hot update, sometimes the interface may appear inconsistent as expected. Need to refresh again.

The reason why I can determine it is windiCss because this problem only started to appear after I joined windiCss. So I want to trouble you to take a look. Check whether the hot update of the entire plug-in may cause memory overflow.

**Comment by anncwb** [comment]
Add a screenshot

![image](https://user-images.githubusercontent.com/28132598/110078023-10910900-7dc2-11eb-8721-b7646d127840.png)

**Comment by anncwb** [comment]
This is a memory overflow after the hot update

**Comment by antfu** [comment]
I am not very familiar with this but took an overview of the code, I don't see an immediate reason that causes the memory leaks. Is that possible on your side to see where consumes most of the memory?

**Comment by anncwb** [comment]
This is provided to me by a user

![image](https://user-images.githubusercontent.com/28132598/110101818-003b5700-7ddf-11eb-909d-e237631656e1.png)

**Comment by anncwb** [comment]
It seems to be the reason for node.js processing

**Comment by anncwb** [comment]
As a comparison, and to ensure that this plug-in is the cause, I will switch back to tailwindui later, and then re-determine

**Comment by anncwb** [comment]
emm.. When switching to tailwindui, this problem is gone. But I still want to use this, tailwindui  compiled for too long. I can only provide one detailed information as much as possible, and then wait to confirm where the problem is

- This problem only occurs when a hot update is triggered when the CSS style is modified. Modifying the ts code does not.
- When the code is saved, and the hot update of the page is not completed, press Save again to trigger the hot update. Sometimes, in order to ensure that the save is successful, the save is performed n times in a row. At this time, the probability of problems will greatly increase.

**Comment by hannoeru** [comment]
Can you provide some info about:
- OS (include 32-bit or 64-bit):
- Memory size:
- Node version:
- Vite version:
- Dev server start command:

**Comment by anncwb** [comment]
> Can you provide some info about:
> 
> * OS (include 32-bit or 64-bit): win10-64
> * Memory size:16G
> * Node version (include 32-bit or 64-bit):node12 64-bit
> * Vite version:2.0.5
> * Dev server start command:yarn dev

The chance of memory overflow appearing on windows is relatively high. In mac pro

**Comment by hannoeru** [comment]
Normal 64-bit Nodejs's memory limit is 1GB, you can increase it by setting:
`"dev": "npx --max_old_space_size=4096 vite dev`
inside `package.json`

**Comment by antfu** [comment]
I am not very familiar with debugging Node, do anyone know how to find which line of code (or stack trace) causes the overflow? Thanks.

/cc @voorjaar any idea of the potential reason for causing overflow in windicss itself?

**Comment by anncwb** [comment]
> Normal 64-bit Nodejs's memory limit is 1GB, you can increase it by setting:
> `"dev": "npx --max_old_space_size=4096 vite dev`
> inside `package.json`


What I posted earlier was the performance in window10. In mac book pro, although there will be no memory overflow, it will cause the page refresh to be very slow. So I think increasing the memory should not solve this problem

**Comment by anncwb** [comment]
To add, this seems to be a superimposed process. When Vite is executed at the beginning, it is very fast, and with each modification of the code, it will slowly start to slow down. In the end the memory overflowed

**Comment by antfu** [comment]
@anncwb is that overflow with continue changing the content or just saving without modifications?

**Comment by antfu** [comment]
Made a try, can you check if it works with v0.6.11?

**Comment by anncwb** [comment]
I will try now

**Comment by anncwb** [comment]
It will take a while to try this. Because it is necessary to simulate real development scenarios as much as possible. So please wait

**Comment by anncwb** [comment]
> @anncwb是继续更改内容还是只是保存而没有修改的溢出？

Continuous modification of content

**Comment by anncwb** [comment]
The effect of this update is obvious on my computer, but mine is mac os, after waiting for other people’s windows test these two days, I continue to report this problem

**Comment by anncwb** [comment]
thank！

**Comment by anncwb** [comment]
@antfu 

I think windicss has been upgraded to 2.3.0. It seems that the memory has been repaired. If it is convenient, I will be testing when you upgrade.

**Comment by antfu** [comment]
Updated as 0.7.0

**Comment by anncwb** [comment]
There are no major problems at the moment. If there is a new memory overflow situation, I will restart the problem. Thank you
