### ISSUE TITLE
[SSR]Get stuck when switch to other page that use `less` pre-processor

### ISSUE THREAD

**Issue by cwxyz007** [windicss/vite-plugin-windicss#63]
Reproduce repo: https://github.com/cwxyz007/vite-windicss-bug

Steps:

1. start dev server

```sh
yarn

yarn dev
```

2. open `http://localhost:3000/`
3. Switch to `About` page

Then, It get stuck.

The main code is here: https://github.com/cwxyz007/vite-windicss-bug/blob/6fbcd29016cdf06ddd036259d99768f429595481/src/pages/About.vue#L24-L28

When I comment this code, It works. Or I remove vite-plugin-windicss, it also works.

**Comment by antfu** [comment]
Should be fixed in the latest version
