### ISSUE TITLE
Forms plugin not working

### ISSUE THREAD

**Issue by HeyImNoxz** [windicss/vite-plugin-windicss#68]
Hi, im using the version 0.6.6 but the forms are still not working for me

its working with your temp bug fix: "preflight enable all" but its making the dev server very slow

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by HeyImNoxz** [comment]
sure here is the reproduction

https://github.com/HeyImNoxz/windicss_login

**Comment by hannoeru** [comment]
I think is windicss can't detect dynamic binding input type,
@antfu maybe we can add a option to enable all or specific attrs?

**Comment by antfu** [comment]
Yes, we do statically scan and the dynamic part can't be covered. In v0.6.10, we support safe listing them by:

```ts
WindiCSS({
  preflight: {
    safelist: ['[type="text"]', '[type="number"]'],
  },
})
```
