### ISSUE TITLE
Webstorm autocomplete + pug does not work

### ISSUE THREAD

**Issue by cliqer** [windicss/vite-plugin-windicss#69]
Is this a bug or am I missing something?

**Comment by antfu** [comment]
Can you provide more context? Thanks

**Comment by cliqer** [comment]
@antfu on Webstorm autocomplete of classes does not work at all like it used to with old tailwind implementation.
I'm also using pug and I assume webstorm needs to find the tailwind classes somewhere compiled to provide autocomplete.
Is there anything like IntelliSense for visual studio code that can work with webstorm?
Do I need to do something else or am I missing an option within the plugin?
Tried with the following options that didn't make any change:
```js
      transformCSS: 'pre',
      preflight: {
        enableAll: true
      }
```
