### ISSUE TITLE
Conditional classes not being generated

### ISSUE THREAD

**Issue by jacobclevenger** [windicss/vite-plugin-windicss#7]
**Problem**
It seems this plugin isn't generating classes for conditional classes in vue templates. For example the following worked when using tailwindcss, but it no longer works with windicss

```html
<div :class="{ 'ml-24': hasSidebar }"></div>
```
If I move it to just a normal class attribute then it works, but obviously no longer produces the desired effet.
```html
<div class="ml-24"></div>
```

Though I'm not sure if this is a problem with windicss or the plugin

**Comment by ElMassimo** [comment]
Thanks for the report! Confirmed it's a problem in the Vite plugin, working on a fix.
