### ISSUE TITLE
typography plugin not working

### ISSUE THREAD

**Issue by loonpwn** [windicss/vite-plugin-windicss#72]
I was testing my webpack windi implementation with the latest versions and the prose code didn't seem to work with the typography plugin, I tested it with this package and same issue.

Within `examples/vue/src/App.vue` put the prose code

```vue
<article class="prose lg:prose-xl prose-red">
    <h1>Garlic with cheese: What the science tells us</h1>
    <p>
      For years parents have espoused the health benefits of eating garlic bread with cheese to their
      children, with the food earning such an iconic status in our culture that kids will often dress
      up as warm, cheesy loaf for Halloween.
    </p>
    <p>
      But a recent study shows that the celebrated appetizer may be linked to a series of rabies cases
      springing up around the country.
    </p>
  </article>
```

`windi.config.ts` add the plugin

```js
plugins: [require('windicss/plugin/typography')],
```

appended on to the `vite.config.ts` - `safelist`

```js
 WindiCSS({
      safelist: 'no-select prose lg:prose-xl prose-red',
    }),
```

![image](https://user-images.githubusercontent.com/5326365/110466797-4e778f80-812a-11eb-874e-e4f544c74683.png)

**Comment by hannoeru** [comment]
Related to https://github.com/windicss/windicss/issues/137

**Comment by loonpwn** [comment]
Ah true, should have checked there first. Thanks @hannoeru 

I'll close this issue for now
