### ISSUE TITLE
Scanning third-party code in node_modules

### ISSUE THREAD

**Issue by loonpwn** [windicss/vite-plugin-windicss#76]
This has come to my attention from this issue: https://github.com/windicss/nuxt-windicss-module/issues/6

If the user is using a third-party component that previously used tailwind styles, there is no way to scan it for the classes.  This is because there is a hard exclude on all node_module files.

```js
function getExcludeGlob() {
    return ['node_modules', '.git', ...scanOptions.exclude]
  }
```

The below code should just work ideally but may require a new option.

```js
scan: {
      dirs: ['node_modules/vue-tailwind-color-picker/']
    }
```

**Comment by mercs600** [comment]
The same issue here, when I want to add my third-party dirs by module:

```js
const contentToPurge = [
  resolve(__dirname, '../components/'),
  resolve(__dirname, '../directives/')
]

  this.nuxt.hook('windicss:config', function (config: any) {
    config.scan.dirs = [...config.scan.dirs, ...contentToPurge]
  })
```

**Comment by productfrontenddeveloper** [comment]
This did not work for me. For your information.

**Comment by antfu** [comment]
With v0.8.0, specifying `scan.exclude` will override the default value instead of appending to it.

```ts
  scan: {
    exclude: ['.git'], // node_modules will no longer been exclude, take your own risk
    dirs: ['node_modules/vue-tailwind-color-picker/']
  }
```
