### ISSUE TITLE
Some classes not working after restart the server

### ISSUE THREAD

**Issue by rashidpathiyil** [windicss/vite-plugin-windicss#79]
Working as expected when added this class, but after the restarting dev server this class not working.
`class="border-opacity-10"`

same issue for this also ``` :class="`md:pl-${paddingLeft}`"  ```

I am working on Vitesse @antfu

**Comment by antfu** [comment]
Can you share a minimal repro? 

Dynamic usages like ```:class="`md:pl-${paddingLeft}\`"``` will not work, unless you list all the possible items or add them to the safelist.

**Comment by FredericoGauz** [comment]
Hi antfu, I where can I find this safelist?

**Comment by hannoeru** [comment]
@FredericoGauz You can set it inside `vite.config.ts`, like:
```ts
plugin: [
  WindiCSS({
    safelist: ['pl-4']
  })
]

**Comment by FredericoGauz** [comment]
Awesome! This will be a live saver for string interpolations. Thank you
