### ISSUE TITLE
Any examples with storybook?

### ISSUE THREAD

**Issue by stecky** [windicss/vite-plugin-windicss#81]
I've tried adding `import 'windi.css'` to preview.js in the .storybook folder, but it won't even start up because it can't find windi.css

I've also tried adding a webpack.config.js using the [Vanilla Webpack](https://windicss.netlify.app/guide/vue.html#vanilla-webpack) example from the documentation.

I am using Vite with [antfu/vitesse](https://github.com/antfu/vitesse) as a starter template

**Comment by antfu** [comment]
Storybook is webpack based and you might need to have a look at https://github.com/windicss/windicss-webpack-plugin
