### ISSUE TITLE
keyframes does not work

### ISSUE THREAD

**Issue by runminlook** [windicss/vite-plugin-windicss#82]
https://windicss.org/utilities/transitions.html#customizing-5

It seems windicss does not process theme.extend.keyframes of tailwind.config.js.

**Comment by antfu** [comment]
Can you share a minimal repro? thanks

**Comment by FredericoGauz** [comment]
I think it should be on the docs that you need to _restart_ vite to have most tailwind related things working after a change.

**Comment by antfu** [comment]
@FredericoGauz Sorry I don't get what you mean. Thanks to tailwin.config.js will be updated automatically without needing to restart the server

**Comment by FredericoGauz** [comment]
Ah, maybe I got it wrong. It is just that I noticed that many changes that I do in the code only work after I restart the server. But since tailwind.config.js is javascript it might be different right?

**Comment by antfu** [comment]
Close for cleaning up. Reopen if you got a proper repro, thanks!
