### ISSUE TITLE
I'm getting an error during vite build

### ISSUE THREAD

**Issue by thelinuxlich** [windicss/vite-plugin-windicss#83]
Am I missing some config? Followed the instruction in README:
```Error: [vite]: Rollup failed to resolve import "virtual:windi.css" from "src/App.jsx".```

**Comment by FredericoGauz** [comment]
Same thing here...

**Comment by antfu** [comment]
What's your plugin's version? Can you provide a minimal repro?

**Comment by FredericoGauz** [comment]
Hi Antony,

I forgot to get back to this issue. It looks like I was using an outdated
version of this plugin. When I manually updated the version in package.json
to the last release (0.8.2) it worked fine.

I think this might be just a matter of (yarn in my case) be installing an
outdated version.

**Comment by thelinuxlich** [comment]
Can confirm the error vanished after this update too!
