### ISSUE TITLE
 @apply does not work with 

### ISSUE THREAD

**Issue by overflowedBuffer** [windicss/vite-plugin-windicss#85]
**Describe the bug**
it seems postcss syntax is not working properly
![image](https://user-images.githubusercontent.com/58886172/110991202-91836e00-8389-11eb-994b-5ab748cba8be.png)
![image](https://user-images.githubusercontent.com/58886172/110991269-a9f38880-8389-11eb-84a3-79552dc3f042.png)

**Minimal Reproductions**
https://github.com/overflowedBuffer/vite-windicss-nuxt-bug-rp
clone this repo
>yarn 
>yarn dev
**Versions**
- vite-plugin-windicss: latest
- vite:latest
- framework(vue/react/svelte/etc): nuxt - vite - windicss

**Additonal Context**

**Comment by schelmo** [comment]
in your nuxt.config.js:
```js
export default {
  windicss: {
    transformCSS: true
  }
...
```
works for me

**Comment by hannoeru** [comment]
Use [nuxt-windicss-module](https://github.com/windicss/nuxt-windicss-module), it will add Nuxt specific custom config for you.
