### ISSUE TITLE
Issue loading CSS with svelte on a cold start

### ISSUE THREAD

**Issue by const-entropy** [windicss/vite-plugin-windicss#91]
When I try this plugin with svelte, it does not load css on a cold start. It loads only after I make some change triggering hmr calls.

I have uploaded a sample repo with my configurations [here](https://github.com/const-entropy/svelte-vite-windicss-ts-/settings).

Am I missing something in my config?

**Comment by schelmo** [comment]
Hi,
the problem is the ```root: "src"``` in your vite.config.js
windicss is then searching for src/src/**/*.{html,vue,md,mdx,pug,jsx,tsx,svelte}
you can either remove your definition of root or, if you need it, change the search dir in your vite.config.js:
```js
windiCss({
  scan: {
    dirs: './'
  }
})
