### ISSUE TITLE
"corePlugins.preflight" in windi.config.ts not working 

### ISSUE THREAD

**Issue by Amorites** [windicss/vite-plugin-windicss#94]
**Describe the bug**
I'm not sure if this is a bug. In tailwind's docs, the way to disable preflight is [here](https://tailwindcss.com/docs/preflight#disabling-preflight), which doesn't work in windi.

It took me a few hours to realize that it should be configured in `vite.config.ts`

**Minimal Reproductions**

```
  // windi.config.ts
  corePlugins: {
     preflight: false,
  }
```

The config won't work as tailwind does.

**Versions**
- vite-plugin-windicss: 0.9.2
- vite: 2.1.2
- framework(vue/react/svelte/etc): vue

**Additonal Context**

**Comment by hannoeru** [comment]
In `vite-plugin-windicss` the preflight option is control by plugin it self, so you need add `preflight: false` to plugin options
```ts
// vite.config.ts
plugins: [
  WindiCSS({
    preflight: false
  })
]
```

**Comment by antfu** [comment]
Update the docs. Thanks for bringing this up
