### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by anncwb** [windicss/vite-plugin-windicss#95]
**Describe the bug**
I didn’t expect this problem to be caused by windicss, and it took me to investigate for a long time. :(

**Minimal Reproductions**
- clone https://github.com/anncwb/server-bug
- yarn && yarn dev
- start server 
- cd ./server.  && yarn start
- Open the browser and find that Vite’s post proxy cannot be sent out

I checked many places, but I didn't expect it to be a problem with this plugin. Back to 0.8.4 the problem disappeared

**Versions**
- vite-plugin-windicss:0.9.2
- vite:2.0.5
- framework(vue/react/svelte/etc):vue

**Additonal Context**

**Comment by anncwb** [comment]
@antfu

**Comment by antfu** [comment]
Can you describe it a bit?

**Comment by anncwb** [comment]
That is, the request for the post interface failed without any response

**Comment by anncwb** [comment]
Can be sure that it was caused by this submission f06d13e097d07ecef81e5f72edb35125180bcc5b

**Comment by anncwb** [comment]
This is some feedback from me, you should understand https://github.com/anncwb/vue-vben-admin/issues/386

**Comment by anncwb** [comment]
@antfu  Hope this is useful for you。 I know the Nuggets way, and the vite-plugin-mock I wrote before also encountered a similar situation. The reason is that body-parser cannot intercept all of them. Only requests that need to be processed by the plug-in can be intercepted. So you need to obtain the body parameters of the post request by yourself
